CREATE SEQUENCE SEQ_MEMBER;

CREATE TABLE TBL_MEMBER(
	ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
	MEMBER_EMAIL VARCHAR2(1000) NOT NULL,
	MEMBER_PASSWORD VARCHAR2(1000) NOT NULL,
	MEMBER_NAME VARCHAR2(1000) NOT NULL,
	MEMBER_AGE NUMBER DEFAULT 0,
	MEMBER_GENDER VARCHAR2(1000) DEFAULT '선택 안함',
	CREATED_DATE DATE DEFAULT SYSDATE,
	UPDATED_DATE DATE DEFAULT SYSDATE
);

INSERT INTO TBL_MEMBER
(ID, MEMBER_EMAIL, MEMBER_PASSWORD, MEMBER_NAME, MEMBER_AGE, MEMBER_GENDER, CREATED_DATE, UPDATED_DATE)
VALUES(SEQ_MEMBER.NEXTVAL, 'test123@gmail.com', '1234', '홍길동', 20, '남자', SYSDATE, SYSDATE
);
INSERT INTO TBL_MEMBER
(ID, MEMBER_EMAIL, MEMBER_PASSWORD, MEMBER_NAME, MEMBER_AGE, MEMBER_GENDER, CREATED_DATE, UPDATED_DATE)
VALUES(SEQ_MEMBER.NEXTVAL, 'test234@naver.com', '2346', '이순신', 40, '남자', SYSDATE, SYSDATE
);
INSERT INTO TBL_MEMBER
(ID, MEMBER_EMAIL, MEMBER_PASSWORD, MEMBER_NAME, MEMBER_AGE, MEMBER_GENDER, CREATED_DATE, UPDATED_DATE)
VALUES(SEQ_MEMBER.NEXTVAL, 'test128@gmail.com', '1234', '한지수', 20, '여자', SYSDATE, SYSDATE
);


SELECT * FROM TBL_MEMBER WHERE MEMBER_EMAIL = ? MEMBER;

