CREATE SEQUENCE SEQ_POST;

CREATE TABLE TBL_POST(
	ID NUMBER CONSTRAINT PK_POST PRIMARY KEY,
	POST_TITLE VARCHAR2(1000) NOT NULL,
	POST_CONTENT VARCHAR2(1000) NOT NULL,
	POST_READ_COUNT NUMBER DEFAULT 0,
	MEMBER_ID NUMBER NOT NULL,
	CREATED_DATE DATE DEFAULT SYSDATE,
	UPDATED_DATE DATE DEFAULT SYSDATE,
	CONSTRAINT FK_POST_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID) ON DELETE CASCADE 
);

INSERT INTO TBL_POST
(ID, POST_TITLE, POST_CONTENT, POST_READ_COUNT, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES(SEQ_POST.NEXTVAL, '테스트제목1', '테스트내용1', 0, 3, SYSDATE, SYSDATE);
INSERT INTO TBL_POST
(ID, POST_TITLE, POST_CONTENT, POST_READ_COUNT, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES(SEQ_POST.NEXTVAL, '테스트제목2', '테스트내용2', 0, 1, SYSDATE, SYSDATE);
INSERT INTO TBL_POST
(ID, POST_TITLE, POST_CONTENT, POST_READ_COUNT, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES(SEQ_POST.NEXTVAL, '테스트제목3', '테스트내용3', 0, 2, SYSDATE, SYSDATE);


SELECT * FROM TBL_POST;


