CREATE SEQUENCE SEQ_PRODUCT;

CREATE TABLE TBL_PRODUCT(
	ID NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY,
	PRODUCT_NAME VARCHAR2(1000),
	PRODUCT_PRICE NUMBER,
	MEMBER_ID NUMBER NOT NULL,
	CONSTRAINT FK_PRODUCT_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID)
);