------
여행계획
------
번호 PK
------
여행명
시작일
종료일
마감일
모집인원
최소인원
비용
모이는 장소 주소
소개내용
대표 파일 경로명 // 하나만 등록되도록 수정
대표 파일 파일명
등록일
등록취소일      // 모집마감일이 지나면 자동 취소
회원번호 FK // 작성자
추천코스번호 FK
생성일자
수정일자

CREATE TABLE TBL_COURSE(
	ID NUMBER CONSTRAINT PK_COURSE PRIMARY KEY,
	NAME VARCHAR2(2000)
);

CREATE TABLE TBL_MEMBER(
	ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
	NAME VARCHAR2(2000)
);

CREATE SEQUENCE SEQ_PLAN;
CREATE TABLE TBL_PLAN(
	ID NUMBER CONSTRAINT PK_PLAN PRIMARY KEY,
	PLAN_NAME VARCHAR2(1000) NOT NULL,
	PLAN_START_DATE DATE DEFAULT SYSDATE,
	PLAN_END_DATE DATE DEFAULT SYSDATE,
	PLAN_MAX_PERSONNEL NUMBER NOT NULL,
	PLAN_MIN_PERSONNEL NUMBER NOT NULL,
	PLAN_PRICE NUMBER NOT NULL,
	PLAN_GATHERING_ADDR VARCHAR2(2000) NOT NULL,
	PLAN_INTRODUCTION VARCHAR2(2000) NOT NULL,
	PLAN_FILE_PATH VARCHAR2(2000) NOT NULL,
	PLAN_FILE_NAME VARCHAR2(2000) NOT NULL,
	PLAN_REGIST_DATE DATE DEFAULT NULL,
	PLAN_REGIST_CANCEL_DATE DATE DEFAULT NULL,
	MEMBER_ID NUMBER NOT NULL,
	COURSE_ID NUMBER NOT NULL,
	CREATE_DATE DATE DEFAULT SYSDATE,
	UPDATE_DATE DATE DEFAULT SYSDATE,
	CONSTRAINT FK_PLAN_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID),
	CONSTRAINT FK_PLAN_COURSE FOREIGN KEY(COURSE_ID)
	REFERENCES TBL_COURSE(ID)
);

-------------------
포함/불포함/준비물 슈퍼
-------------------
번호 PK
-------------------
내용
생성일자
수정일자


CREATE SEQUENCE SEQ_CONSIDER;
CREATE TABLE TBL_CONSIDER (
	ID NUMBER CONSTRAINT PK_CONSIDER PRIMARY KEY,
	CONSIDER_CONTENT VARCHAR2(1000) DEFAULT '',
	CREATE_DATE DATE DEFAULT SYSDATE,
	UPDATE_DATE DATE DEFAULT SYSDATE
);

--------------- ----------------- ------------------
포함 				불포함 				준비물
--------------- ----------------- ------------------

번호 PK FK 		번호 PK FK 			번호 PK FK
여행계획번호 FK 	여행계획번호 FK 		여행계획번호 FK

CREATE SEQUENCE SEQ_INCLUDE;
CREATE TABLE TBL_INCLUDE (
	ID NUMBER CONSTRAINT PK_INCLUDE PRIMARY KEY,
	PLAN_ID NUMBER NOT NULL,
	CONSTRAINT FK_INCLUDE_CONSIDER FOREIGN KEY (ID)
	REFERENCES TBL_CONSIDER(ID),
	CONSTRAINT FK_INCLUDE_PLAN FOREIGN KEY (PLAN_ID)
	REFERENCES TBL_PLAN(ID)
);

CREATE SEQUENCE SEQ_EXCLUDE;
CREATE TABLE TBL_EXCLUDE (
	ID NUMBER CONSTRAINT PK_EXCLUDE PRIMARY KEY,
	PLAN_ID NUMBER NOT NULL,
	CONSTRAINT FK_EXCLUDE_CONSIDER FOREIGN KEY (ID)
	REFERENCES TBL_CONSIDER(ID),
	CONSTRAINT FK_EXCLUDE_PLAN FOREIGN KEY (PLAN_ID)
	REFERENCES TBL_PLAN(ID)
);

CREATE SEQUENCE SEQ_PREPARE;
CREATE TABLE TBL_PREPARE (
	ID NUMBER CONSTRAINT PK_PREPARE PRIMARY KEY,
	PLAN_ID NUMBER NOT NULL,
	CONSTRAINT FK_PREPARE_CONSIDER FOREIGN KEY (ID)
	REFERENCES TBL_CONSIDER(ID),
	CONSTRAINT FK_PREPARE_PLAN FOREIGN KEY (PLAN_ID)
	REFERENCES TBL_PLAN(ID)
);

----------
찜 슈퍼
----------
번호 PK
-----------
생성일자
수정일자

CREATE SEQUENCE SEQ_CART;
CREATE TABLE TBL_CART (
	ID NUMBER CONSTRAINT PK_CART PRIMARY KEY,
	CREATE_DATE DATE DEFAULT SYSDATE,
	UPDATE_DATE DATE DEFAULT SYSDATE
);

--------------- ------------------
추천코스 찜 		여행계획 찜
--------------- ------------------

회원번호 FK 		회원번호 FK
추천여행번호 FK 	여행계획번호 FK

CREATE SEQUENCE SEQ_COURSE_CART;
CREATE TABLE TBL_COURSE_CART (
	ID NUMBER CONSTRAINT PK_COURSE_CART PRIMARY KEY,
	MEMBER_ID NUMBER NOT NULL,
	COURSE_ID NUMBER NOT NULL,
	CONSTRAINT FK_COURSE_CART_CART FOREIGN KEY (ID)
	REFERENCES TBL_CART(ID),
	CONSTRAINT FK_COURSE_CART_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID),
	CONSTRAINT FK_COURSE_CART_COURSE FOREIGN KEY(COURSE_ID)
	REFERENCES TBL_COURSE(ID)
);

CREATE SEQUENCE SEQ_PLAN_CART;
CREATE TABLE TBL_PLAN_CART (
	ID NUMBER CONSTRAINT PK_PLAN_CART PRIMARY KEY,
	MEMBER_ID NUMBER NOT NULL,
	PLAN_ID NUMBER NOT NULL,
	CONSTRAINT FK_PLAN_CART_CART FOREIGN KEY (ID)
	REFERENCES TBL_CART(ID),
	CONSTRAINT FK_PLAN_CART_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID),
	CONSTRAINT FK_PLAN_CART_PLAN FOREIGN KEY(PLAN_ID)
	REFERENCES TBL_PLAN(ID)
);

-------------
일정 슈퍼
------------
번호 PK
-----------
날짜
일정내용
생성일자
수정일자

CREATE SEQUENCE SEQ_SCHEDULE;
CREATE TABLE TBL_SCHEDULE (
	ID NUMBER CONSTRAINT PK_SCHEDULE PRIMARY KEY,
	SCHEDULE_DATE DATE NOT NULL,
	SCHEDULE_CONTENT VARCHAR2(2000) NOT NULL,
	CREATE_DATE DATE DEFAULT SYSDATE,
	UPDATE_DATE DATE DEFAULT SYSDATE
);


-------------
여행계획 일정
------------
번호 PK
-----------
여행계획번호 FK

CREATE SEQUENCE SEQ_PLAN_SCHEDULE;
CREATE TABLE TBL_PLAN_SCHEDULE(
	ID NUMBER CONSTRAINT PK_PLAN_SCHEDULE PRIMARY KEY,
	PLAN_ID NUMBER NOT NULL,
    CONSTRAINT FK_PLAN_SCHEDULE_SCHEDULE FOREIGN KEY(ID)
    REFERENCES TBL_SCHEDULE(ID),
	CONSTRAINT FK_PLAN_SCHEDULE_PLAN FOREIGN KEY(PLAN_ID)
	REFERENCES TBL_PLAN(ID)
);

------------
참여
------------
번호
-------------
회원번호 FK
여행계획번호 FK
생성일자
수정일자

CREATE SEQUENCE SEQ_PARTICIPANT;
CREATE TABLE TBL_PARTICIPANT (
	ID NUMBER CONSTRAINT PK_PARTICIPANT PRIMARY KEY,
	MEMBER_ID NUMBER NOT NULL,
	PLAN_ID NUMBER NOT NULL,
	CREATE_DATE DATE DEFAULT SYSDATE,
	UPDATE_DATE DATE DEFAULT SYSDATE,
	CONSTRAINT FK_PARTICIPANT_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID),
	CONSTRAINT FK_PARTICIPANT_PLAN FOREIGN KEY(PLAN_ID)
	REFERENCES TBL_PLAN(ID)
);

--------------
질문
-------------
번호 PK
--------------
내용
여행계획 번호 FK
생성일자
수정일자

CREATE SEQUENCE SEQ_QUESTION;
CREATE TABLE TBL_QUESTION (
	ID NUMBER CONSTRAINT PK_QEUSTION PRIMARY KEY,
	MEMBER_ID NUMBER NOT NULL,
	PLAN_ID NUMBER NOT NULL,
	CREATE_DATE DATE DEFAULT SYSDATE,
	UPDATE_DATE DATE DEFAULT SYSDATE,
	CONSTRAINT FK_QEUSTION_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID),
	CONSTRAINT FK_QEUSTION_PLAN FOREIGN KEY(PLAN_ID)
	REFERENCES TBL_PLAN(ID)
);

--------------
답글
-------------
번호 PK
--------------
내용
질문 번호 FK
생성일자
수정일자

CREATE SEQUENCE SEQ_ANSWER;
CREATE TABLE TBL_ANSWER (
	ID NUMBER CONSTRAINT PK_ANSWER PRIMARY KEY,
	ANSWER_CONTENT VARCHAR2(2000) NOT NULL,
	MEMBER_ID NUMBER NOT NULL,
	QUESTION_ID NUMBER NOT NULL,
	CONSTRAINT FK_ANSWER_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID),
	CONSTRAINT FK_ANSWER_QEUSTION FOREIGN KEY(QUESTION_ID)
	REFERENCES TBL_QUESTION(ID)
);

----------------
결제내역
---------------
번호
---------------
단가
결제인원
사용포인트      // 단가 * 결제인원 - 사용포인트 :: 최종결제금액. 최종결제금액 / 100 :: 적립포인트
적립포인트
결제수단
카드사번호
회원번호 FK
모집여행번호 FK
생성일자
수정일자

CREATE SEQUENCE SEQ_PAY;
CREATE TABLE TBL_PAY(
	ID NUMBER CONSTRAINT PK_PAY PRIMARY KEY,
	PAY_PRICE NUMBER DEFAULT 0,
	PAY_PERSONNEL NUMBER DEFAULT 1,
	PAY_USED_POINT NUMBER DEFAULT 0,
	PAY_NEW_POINT NUMBER DEFAULT 0,
	PAY_METHOD NUMBER(3) NOT NULL,
	PAY_CARD_COMPANY NUMBER(3) NOT NULL,
	MEMBER_ID NUMBER NOT NULL,
	PLAN_ID NUMBER NOT NULL,
	CREATE_DATE DATE DEFAULT SYSDATE,
	UPDATE_DATE DATE DEFAULT SYSDATE,
	CONSTRAINT FK_PAY_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID),
	CONSTRAINT FK_PAY_PLAN FOREIGN KEY(PLAN_ID)
	REFERENCES TBL_PLAN(ID)
);


--------------------
피드 슈퍼키
-------------------
번호 PK
-------------------
내용
생성일자
수정일자

CREATE SEQUENCE SEQ_FEED;
CREATE TABLE TBL_FEED(
	ID NUMBER CONSTRAINT PK_FEED PRIMARY KEY,
	CREATE_DATE DATE DEFAULT SYSDATE,
	UPDATE_DATE DATE DEFAULT SYSDATE
);

-------------------- -------------------- ----------------------
일반피드 				같이해요피드 				후기
-------------------- -------------------- -----------------------
번호 PK FK 			번호 PK FK 				번호 PK FK
---------------------- ---------------------- ----------------------
회원번호 FK 			회원번호 FK 				평가 점수
											회원번호 FK
											여행계획 번호 FK

CREATE SEQUENCE SEQ_GEN_FEED;
CREATE TABLE TBL_GEN_FEED(
	ID NUMBER CONSTRAINT PK_GEN_FEED PRIMARY KEY,
	MEMBER_ID NUMBER NOT NULL,
	CONSTRAINT FK_GEN_FEED_FEED FOREIGN KEY(ID)
	REFERENCES TBL_FEED(ID),
	CONSTRAINT FK_GEN_FEED_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID)
);											

CREATE SEQUENCE SEQ_WITH_FEED;
CREATE TABLE TBL_WITH_FEED(
	ID NUMBER CONSTRAINT PK_WITH_FEED PRIMARY KEY,
	MEMBER_ID NUMBER NOT NULL,
	CONSTRAINT FK_WITH_FEED_FEED FOREIGN KEY(ID)
	REFERENCES TBL_FEED(ID),
	CONSTRAINT FK_WITH_FEED_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID)
);											
		

CREATE SEQUENCE SEQ_REAL_FEED;
CREATE TABLE TBL_REAL_FEED(
	ID NUMBER CONSTRAINT PK_REAL_FEED PRIMARY KEY,
	REAL_FEED_STAR NUMBER(1) DEFAULT 0,
	MEMBER_ID NUMBER NOT NULL,
	PLAN_ID NUMBER NOT NULL,
	CONSTRAINT FK_REAL_FEED_FEED FOREIGN KEY(ID)
	REFERENCES TBL_FEED(ID),
	CONSTRAINT FK_REAL_FEED_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID),
	CONSTRAINT FK_REAL_FEED_PLAN FOREIGN KEY(PLAN_ID)
	REFERENCES TBL_PLAN(ID)
);											
		
											
------------------
태그 슈퍼
------------------
번호 PK
-----------------
내용
생성일자
수정일자

CREATE SEQUENCE SEQ_TAG;
CREATE TABLE TBL_TAG(
	ID NUMBER CONSTRAINT PK_TAG PRIMARY KEY,
	TAG_CONTENT VARCHAR2(2000) NOT NULL,
	CREATE_DATE DATE DEFAULT SYSDATE,
	UPDATE_DATE DATE DEFAULT SYSDATE
);


---------------- --------------------
일반/같이 피드태그     후기 태그
---------------- ---------------------
번호 PK FK         번호 PK FK
---------------- ---------------------
피드 번호 FK        후기번호 FK


CREATE SEQUENCE SEQ_GEN_TAG;
CREATE TABLE TBL_GEN_TAG(
	ID NUMBER CONSTRAINT PK_GEN_TAG PRIMARY KEY,
	FEED_ID NUMBER NOT NULL,
	CONSTRAINT FK_GEN_TAG_TAG FOREIGN KEY(ID)
	REFERENCES TBL_TAG(ID),
	CONSTRAINT FK_GEN_TAG_FEED FOREIGN KEY(FEED_ID)
	REFERENCES TBL_FEED(ID)
);											

CREATE SEQUENCE SEQ_WITH_TAG;
CREATE TABLE TBL_WITH_TAG(
	ID NUMBER CONSTRAINT PK_WITH_TAG PRIMARY KEY,
	FEED_ID NUMBER NOT NULL,
	CONSTRAINT FK_WITH_TAG_TAG FOREIGN KEY(ID)
	REFERENCES TBL_TAG(ID),
	CONSTRAINT FK_WITH_TAG_FEED FOREIGN KEY(FEED_ID)
	REFERENCES TBL_FEED(ID)
);											


CREATE SEQUENCE SEQ_REAL_TAG;
CREATE TABLE TBL_REAL_TAG(
	ID NUMBER CONSTRAINT PK_REAL_TAG PRIMARY KEY,
	FEED_ID NUMBER NOT NULL,
	CONSTRAINT FK_REAL_TAG_TAG FOREIGN KEY(ID)
	REFERENCES TBL_TAG(ID),
	CONSTRAINT FK_REAL_TAG_FEED FOREIGN KEY(FEED_ID)
	REFERENCES TBL_FEED(ID)
);											



-----------------
파일 슈퍼
-----------------
번호 PK
경로이름
파일이름
크기
생성일자
수정일자


CREATE SEQUENCE SEQ_FILE;
CREATE TABLE TBL_FILE(
	ID NUMBER CONSTRAINT PK_FILE PRIMARY KEY,
	FILE_PATH VARCHAR2(1000) NOT NULL,
	FILE_NAME VARCHAR2(1000) NOT NULL,
	FILE_SIZE VARCHAR2(200)  DEFAULT '',
	CREATE_DATE DATE DEFAULT SYSDATE,
	UPDATE_DATE DATE DEFAULT SYSDATE
);

---------------- ----------------
일반/같이 피드 파일    후기 파일
---------------- ----------------
번호 PK FK          번호 PK FK
---------------- ----------------
피드 번호 FK         후기 번호 FK



CREATE SEQUENCE SEQ_GEN_FILE;
CREATE TABLE TBL_GEN_FILE(
	ID NUMBER CONSTRAINT PK_GEN_FILE PRIMARY KEY,
	GEN_FEED_ID NUMBER NOT NULL,
	CONSTRAINT FK_GEN_FILE_FILE FOREIGN KEY(ID)
	REFERENCES TBL_FILE(ID),
	CONSTRAINT FK_GEN_FILE_GEN_FEED FOREIGN KEY(GEN_FEED_ID)
	REFERENCES TBL_GEN_FEED(ID)
);											

CREATE SEQUENCE SEQ_WITH_FILE;
CREATE TABLE TBL_WITH_FILE(
	ID NUMBER CONSTRAINT PK_WITH_FILE PRIMARY KEY,
	WITH_FEED_ID NUMBER NOT NULL,
	CONSTRAINT FK_WITH_FILE_FILE FOREIGN KEY(ID)
	REFERENCES TBL_FILE(ID),
	CONSTRAINT FK_WITH_FILE_WITH_FEED FOREIGN KEY(WITH_FEED_ID)
	REFERENCES TBL_WITH_FEED(ID)
);											


CREATE SEQUENCE SEQ_REAL_FILE;
CREATE TABLE TBL_REAL_FILE(
	ID NUMBER CONSTRAINT PK_REAL_FILE PRIMARY KEY,
	REAL_FEED_ID NUMBER NOT NULL,
	CONSTRAINT FK_REAL_FILE_FILE FOREIGN KEY(ID)
	REFERENCES TBL_FILE(ID),
	CONSTRAINT FK_REAL_FILE_REAL_FEED FOREIGN KEY(REAL_FEED_ID)
	REFERENCES TBL_REAL_FEED(ID)
);											





-----------------
댓글 슈퍼
-----------------
번호 PK
-----------------
내용
생성일자
수정일자

CREATE SEQUENCE SEQ_REPLY;
CREATE TABLE TBL_REPLY(
	ID NUMBER CONSTRAINT PK_REPLY PRIMARY KEY,
	REPLY_CONTENT VARCHAR2(2000) NOT NULL,
	CREATE_DATE DATE DEFAULT SYSDATE,
	UPDATE_DATE DATE DEFAULT SYSDATE
);


--------------------- ----------------------
일반/같이 피드 댓글         후기 댓글
---------------------- -----------------------
번호 PK FK              번호 PK FK
---------------------- -----------------------
피드번호 FK               후기번호 FK
회원번호 FK               회원번호 FK



CREATE SEQUENCE SEQ_GEN_REPLY;
CREATE TABLE TBL_GEN_REPLY(
	ID NUMBER CONSTRAINT PK_GEN_REPLY PRIMARY KEY,
	MEMBER_ID NUMBER NOT NULL,
	GEN_FEED_ID NUMBER NOT NULL,
	CONSTRAINT FK_GEN_REPLY_REPLY FOREIGN KEY(ID)
	REFERENCES TBL_REPLY(ID),
	CONSTRAINT FK_GEN_REPLY_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID),
	CONSTRAINT FK_GEN_REPLY_GEN_FEED FOREIGN KEY(GEN_FEED_ID)
	REFERENCES TBL_GEN_FEED(ID)
);											

CREATE SEQUENCE SEQ_WITH_REPLY;
CREATE TABLE TBL_WITH_REPLY(
	ID NUMBER CONSTRAINT PK_WITH_REPLY PRIMARY KEY,
	MEMBER_ID NUMBER NOT NULL,
	WITH_FEED_ID NUMBER NOT NULL,
	CONSTRAINT FK_WITH_REPLY_REPLY FOREIGN KEY(ID)
	REFERENCES TBL_REPLY(ID),
	CONSTRAINT FK_WITH_REPLY_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID),
	CONSTRAINT FK_WITH_REPLY_WITH_FEED FOREIGN KEY(WITH_FEED_ID)
	REFERENCES TBL_WITH_FEED(ID)
);											


CREATE SEQUENCE SEQ_REAL_REPLY;
CREATE TABLE TBL_REAL_REPLY(
	ID NUMBER CONSTRAINT PK_REAL_REPLY PRIMARY KEY,
	MEMBER_ID NUMBER NOT NULL,
	REAL_FEED_ID NUMBER NOT NULL,
	CONSTRAINT FK_REAL_REPLY_REPLY FOREIGN KEY(ID)
	REFERENCES TBL_REPLY(ID),
	CONSTRAINT FK_REAL_REPLY_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID),
	CONSTRAINT FK_REAL_REPLY_REAL_FEED FOREIGN KEY(REAL_FEED_ID)
	REFERENCES TBL_REAL_FEED(ID)
);											


---------------------
후기 좋아요
---------------------
번호 PK
----------------------
후기번호 FK
회원번호 FK

CREATE SEQUENCE SEQ_REAL_GOOD;
CREATE TABLE TBL_REAL_GOOD(
	ID NUMBER CONSTRAINT PK_REAL_GOOD PRIMARY KEY,
	MEMBER_ID NUMBER NOT NULL,
	REAL_FEED_ID NUMBER NOT NULL,
	CONSTRAINT FK_REAL_GOOD_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID),
	CONSTRAINT FK_REAL_GOOD_REAL_FEED FOREIGN KEY(REAL_FEED_ID)
	REFERENCES TBL_REAL_FEED(ID)
);											


