INSERT INTO TBL_CATEGORY_A
(ID, CATEGORY_A_NAME)
VALUES (SEQ_CATEGORY_A.NEXTVAL, '서비스업');

INSERT INTO TBL_CATEGORY_A
(ID, CATEGORY_A_NAME)
VALUES (SEQ_CATEGORY_A.NEXTVAL, '제조·화학');

INSERT INTO TBL_CATEGORY_A
(ID, CATEGORY_A_NAME)
VALUES (SEQ_CATEGORY_A.NEXTVAL, 'IT·웹·통신');

INSERT INTO TBL_CATEGORY_A
(ID, CATEGORY_A_NAME)
VALUES (SEQ_CATEGORY_A.NEXTVAL, '은행·금융업');

INSERT INTO TBL_CATEGORY_A
(ID, CATEGORY_A_NAME)
VALUES (SEQ_CATEGORY_A.NEXTVAL, '미디어·디자인');

INSERT INTO TBL_CATEGORY_A
(ID, CATEGORY_A_NAME)
VALUES (SEQ_CATEGORY_A.NEXTVAL, '교육업');

INSERT INTO TBL_CATEGORY_A
(ID, CATEGORY_A_NAME)
VALUES (SEQ_CATEGORY_A.NEXTVAL, '의료·제약·복지');

INSERT INTO TBL_CATEGORY_A
(ID, CATEGORY_A_NAME)
VALUES (SEQ_CATEGORY_A.NEXTVAL, '판매·유통');

INSERT INTO TBL_CATEGORY_A
(ID, CATEGORY_A_NAME)
VALUES (SEQ_CATEGORY_A.NEXTVAL, '건설업');

INSERT INTO TBL_CATEGORY_A
(ID, CATEGORY_A_NAME)
VALUES (SEQ_CATEGORY_A.NEXTVAL, '기관·협회');



