INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '오류문의', '프로그램 업로드 제한 사유를 알고 싶습니다.', '처리완료', 60);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '이용문의', '초대 코드가 적용되지 않습니다.', '처리완료', 99);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '이용문의', '오류 코드 500이 반복됩니다.', '처리대기', 41);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '기타', '오류 코드 500이 반복됩니다.', '처리완료', 93);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '오류문의', '오류 코드 500이 반복됩니다.', '처리대기', 30);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '오류문의', '프로그램 업로드 제한 사유를 알고 싶습니다.', '처리대기', 14);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '계정문의', '사업자등록증 인증이 되지 않습니다. 해결 부탁드립니다.', '처리완료', 82);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '오류문의', '새로운 기능 추가 예정이 있는지 궁금합니다.', '처리대기', 92);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '오류문의', '회원가입이 정상적으로 되지 않습니다.', '처리대기', 78);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '이용문의', '프로그램 업로드 제한 사유를 알고 싶습니다.', '처리대기', 47);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '이용문의', '프로그램 업로드 제한 사유를 알고 싶습니다.', '처리완료', 76);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '이용문의', '이용약관에 대한 추가 설명이 필요합니다.', '처리대기', 49);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '기타', '프로그램 업로드 제한 사유를 알고 싶습니다.', '처리완료', 89);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '기타', '회원가입이 정상적으로 되지 않습니다.', '처리대기', 4);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '오류문의', '초대 코드가 적용되지 않습니다.', '처리대기', 65);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '이용문의', '내 개인정보를 수정하고 싶습니다.', '처리완료', 61);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '기타', '프로그램 등록 취소를 원합니다.', '처리대기', 91);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '기타', '프로그램 등록 취소를 원합니다.', '처리대기', 85);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '이용문의', '결제 관련 문의드립니다.', '처리완료', 12);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '이용문의', '서비스 이용 중 오류가 발생했습니다. 확인 부탁드립니다.', '처리대기', 48);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '이용문의', '오류 코드 500이 반복됩니다.', '처리대기', 22);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '기타', '초대 코드가 적용되지 않습니다.', '처리대기', 95);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '계정문의', '초대 코드가 적용되지 않습니다.', '처리완료', 74);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '오류문의', '계정 이메일을 재설정하고 싶습니다.', '처리완료', 27);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '기타', '오류 코드 500이 반복됩니다.', '처리대기', 45);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '계정문의', '업로드했던 이미지를 다운로드 받고싶습니다.', '처리완료', 73);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '계정문의', '내 개인정보를 수정하고 싶습니다.', '처리대기', 68);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '이용문의', '내 개인정보를 수정하고 싶습니다.', '처리완료', 10);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '계정문의', '결제 관련 문의드립니다.', '처리완료', 73);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '오류문의', '새로운 기능 추가 예정이 있는지 궁금합니다.', '처리대기', 6);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '오류문의', '기업 인증 방법을 다시 설명해주세요.', '처리완료', 43);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '이용문의', '프로그램 업로드 제한 사유를 알고 싶습니다.', '처리대기', 74);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '오류문의', '내 개인정보를 수정하고 싶습니다.', '처리완료', 18);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '기타', '사업자등록증 인증이 되지 않습니다. 해결 부탁드립니다.', '처리완료', 72);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '오류문의', '서비스 이용 중 오류가 발생했습니다. 확인 부탁드립니다.', '처리완료', 25);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '계정문의', '계정 이메일을 재설정하고 싶습니다.', '처리완료', 47);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '오류문의', '새로운 기능 추가 예정이 있는지 궁금합니다.', '처리완료', 21);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '기타', '업로드했던 이미지를 다운로드 받고싶습니다.', '처리완료', 49);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '오류문의', '초대 코드가 적용되지 않습니다.', '처리대기', 29);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '기타', '서비스 이용 중 오류가 발생했습니다. 확인 부탁드립니다.', '처리완료', 66);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '이용문의', '초대 코드가 적용되지 않습니다.', '처리대기', 38);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '이용문의', '서비스 이용 중 오류가 발생했습니다. 확인 부탁드립니다.', '처리대기', 21);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '기타', '계정이 잠겼습니다. 해결 방법을 알려주세요.', '처리대기', 2);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '오류문의', '오류 코드 500이 반복됩니다.', '처리대기', 59);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '이용문의', '오류 코드 500이 반복됩니다.', '처리대기', 31);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '기타', '프로그램 업로드 제한 사유를 알고 싶습니다.', '처리대기', 36);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '계정문의', '업로드했던 이미지를 다운로드 받고싶습니다.', '처리대기', 43);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '오류문의', '결제 관련 문의드립니다.', '처리대기', 68);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '기타', '초대 코드가 적용되지 않습니다.', '처리완료', 86);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '계정문의', '계정이 잠겼습니다. 해결 방법을 알려주세요.', '처리완료', 87);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '기타', '초대 코드가 적용되지 않습니다.', '처리완료', 45);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '이용문의', '서비스 이용 중 오류가 발생했습니다. 확인 부탁드립니다.', '처리완료', 11);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '이용문의', '계정이 잠겼습니다. 해결 방법을 알려주세요.', '처리대기', 43);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '이용문의', '업로드했던 이미지를 다운로드 받고싶습니다.', '처리완료', 100);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '오류문의', '업로드했던 이미지를 다운로드 받고싶습니다.', '처리대기', 95);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '이용문의', '프로그램 업로드 제한 사유를 알고 싶습니다.', '처리대기', 34);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '기타', '회원가입이 정상적으로 되지 않습니다.', '처리완료', 22);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '기타', '계정이 잠겼습니다. 해결 방법을 알려주세요.', '처리대기', 84);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '이용문의', '초대 코드가 적용되지 않습니다.', '처리완료', 80);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '기타', '초대 코드가 적용되지 않습니다.', '처리대기', 85);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '계정문의', '서비스 이용 중 오류가 발생했습니다. 확인 부탁드립니다.', '처리대기', 56);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '계정문의', '회원가입이 정상적으로 되지 않습니다.', '처리완료', 31);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '기타', '사업자등록증 인증이 되지 않습니다. 해결 부탁드립니다.', '처리완료', 14);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '계정문의', '업로드했던 이미지를 다운로드 받고싶습니다.', '처리완료', 22);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '계정문의', '회원가입이 정상적으로 되지 않습니다.', '처리대기', 94);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '계정문의', '계정이 잠겼습니다. 해결 방법을 알려주세요.', '처리완료', 55);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '기타', '이용약관에 대한 추가 설명이 필요합니다.', '처리대기', 83);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '계정문의', '계정이 잠겼습니다. 해결 방법을 알려주세요.', '처리완료', 7);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '기타', '사업자등록증 인증이 되지 않습니다. 해결 부탁드립니다.', '처리대기', 11);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '계정문의', '이용약관에 대한 추가 설명이 필요합니다.', '처리완료', 11);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '기타', '서비스 이용 중 오류가 발생했습니다. 확인 부탁드립니다.', '처리대기', 63);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '오류문의', '초대 코드가 적용되지 않습니다.', '처리대기', 59);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '계정문의', '초대 코드가 적용되지 않습니다.', '처리대기', 69);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '계정문의', '회원가입이 정상적으로 되지 않습니다.', '처리완료', 41);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '오류문의', '오류 코드 500이 반복됩니다.', '처리완료', 47);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '오류문의', '회원가입이 정상적으로 되지 않습니다.', '처리완료', 8);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '오류문의', '사업자등록증 인증이 되지 않습니다. 해결 부탁드립니다.', '처리대기', 3);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '이용문의', '초대 코드가 적용되지 않습니다.', '처리대기', 71);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '이용문의', '결제 관련 문의드립니다.', '처리완료', 91);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '이용문의', '프로그램 업로드 제한 사유를 알고 싶습니다.', '처리대기', 81);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '기타', '사업자등록증 인증이 되지 않습니다. 해결 부탁드립니다.', '처리완료', 76);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '이용문의', '프로그램 등록 취소를 원합니다.', '처리완료', 52);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '계정문의', '프로그램 등록 취소를 원합니다.', '처리완료', 32);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '오류문의', '새로운 기능 추가 예정이 있는지 궁금합니다.', '처리완료', 56);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '계정문의', '새로운 기능 추가 예정이 있는지 궁금합니다.', '처리대기', 9);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '계정문의', '프로그램 등록 취소를 원합니다.', '처리완료', 91);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '기타', '오류 코드 500이 반복됩니다.', '처리대기', 50);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '기타', '결제 관련 문의드립니다.', '처리대기', 80);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '오류문의', '사업자등록증 인증이 되지 않습니다. 해결 부탁드립니다.', '처리완료', 86);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '계정문의', '이용약관에 대한 추가 설명이 필요합니다.', '처리완료', 34);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '기타', '새로운 기능 추가 예정이 있는지 궁금합니다.', '처리대기', 58);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '계정문의', '서비스 이용 중 오류가 발생했습니다. 확인 부탁드립니다.', '처리완료', 68);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '기타', '이용약관에 대한 추가 설명이 필요합니다.', '처리대기', 77);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '이용문의', '기업 인증 방법을 다시 설명해주세요.', '처리대기', 23);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '오류문의', '새로운 기능 추가 예정이 있는지 궁금합니다.', '처리완료', 51);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '이용문의', '오류 코드 500이 반복됩니다.', '처리완료', 81);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '이용문의', '오류 코드 500이 반복됩니다.', '처리완료', 4);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '계정문의', '계정이 잠겼습니다. 해결 방법을 알려주세요.', '처리대기', 34);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '계정문의', '새로운 기능 추가 예정이 있는지 궁금합니다.', '처리완료', 64);

INSERT INTO TBL_COMPANY_INQUIRY
(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID)
VALUES (SEQ_COMPANY_INQUIRY.NEXTVAL, '이용문의', '사업자등록증 인증이 되지 않습니다. 해결 부탁드립니다.', '처리완료', 54);
