INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '액셀러레이터주식회사', '924-61-96312', '2007-04-11', 196, '553 창읍', 'Suite 306', 'C:\upload\logo1.png', 'www.xn---xn--2i4b-9f82bnzr.ne.kr', 'C:\upload\certificate1.png', '사회적 책임을 다하며, 글로벌 리더로 성장하는 기업입니다.', '자기계발을 위한 교육비 지원', '직원의 의견을 적극 반영하는 문화', '조준서');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '스마트글로벌', '662-26-55453', '2009-07-22', 100, '91439 중계읍', 'Apt. 338', 'C:\upload\logo3.png', 'www.xn---xn--2i4b-f250bs14g.co.kr', 'C:\upload\certificate3.png', '사회적 책임을 다하며, 글로벌 리더로 성장하는 기업입니다.', '해외 연수 기회와 글로벌 커리어 발전 지원', '팀워크와 협업을 중시하는 문화', '정하은');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '테크컴퍼니', '338-21-65490', '2021-06-08', 162, '8235 창면', 'Apt. 620', 'C:\upload\logo3.png', 'www.xn---xn--vy8b-fm92bt9i.ne.kr', 'C:\upload\certificate3.png', '지속 가능한 발전을 위해 끊임없이 노력하는 회사입니다.', '연 2회 워크숍과 팀 빌딩 활동', '사회적 책임을 다하는 윤리적 기업 문화', '최현준');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '이노베이션컴퍼니', '485-20-42814', '2005-12-29', 136, '13692 연산면', 'Suite 057', 'C:\upload\logo3.png', 'www.xn---xn--vk5b-9f82bx0r.or.kr', 'C:\upload\certificate3.png', '항상 변화하는 시장에 민첩하게 대응하는 기업입니다.', '편리한 사내 식사 제공 및 간식 지원', '팀워크와 협업을 중시하는 문화', '김지훈');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '아이디어네트웍', '554-66-16314', '2010-07-08', 170, '449 검단면', 'Suite 369', 'C:\upload\logo2.png', 'www.xn---xn--zf0b-fm92bt9i.ne.kr', 'C:\upload\certificate5.png', '지속 가능한 발전을 위해 끊임없이 노력하는 회사입니다.', '직원 건강을 위한 헬스케어 프로그램 제공', '사회적 책임을 다하는 윤리적 기업 문화', '장우진');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '크리에이티브협회', '752-84-09859', '2024-12-04', 149, '1061 중계동', 'Apt. 871', 'C:\upload\logo1.png', 'www.xn---xn--bh3b-9f82bx0r.biz', 'C:\upload\certificate3.png', '창의적이고 혁신적인 아이디어로 미래를 준비하는 기업입니다.', '해외 연수 기회와 글로벌 커리어 발전 지원', '개인과 팀의 성취를 함께 축하하는 문화', '정은주');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '바이오랩', '643-07-40511', '2010-12-11', 138, '09210 동탄읍', 'Apt. 017', 'C:\upload\logo1.png', 'www.xn---xn--2x8b-9f82bnzr.info', 'C:\upload\certificate3.png', '탁월한 기술력으로 다양한 산업 분야에 기여하는 기업입니다.', '편리한 사내 식사 제공 및 간식 지원', '창의적인 아이디어를 존중하는 문화', '송민준');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '글로벌벤처', '901-65-09932', '2018-06-10', 15, '297 방배면', 'Suite 244', 'C:\upload\logo2.png', 'www.xn---xn--2y5b-9f82biy7g.net', 'C:\upload\certificate1.png', '지속 가능한 발전을 위해 끊임없이 노력하는 회사입니다.', '연 2회 워크숍과 팀 빌딩 활동', '개방적이고 수평적인 조직 문화', '황민준');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '액셀러레이터컨설팅', '028-94-53520', '2019-11-02', 160, '3497 상읍', 'Apt. 103', 'C:\upload\logo2.png', 'www.xn---xn--o26b-fv01bz4x.biz', 'C:\upload\certificate2.png', '새로운 도전을 통해 글로벌 시장을 선도하는 기업입니다.', '결혼 및 출산, 육아 지원 프로그램 제공', '지속 가능한 발전을 추구하는 문화', '오건우');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '글로벌테크놀로지', '718-37-03497', '2025-02-08', 97, '396 중계면', 'Suite 263', 'C:\upload\logo2.png', 'www.xn---xn--9v2b-9f82bnzr.org', 'C:\upload\certificate5.png', '기업의 성장이 곧 직원의 성장이라는 믿음을 가진 회사입니다.', '해외 연수 기회와 글로벌 커리어 발전 지원', '개인과 팀의 성취를 함께 축하하는 문화', '장예준');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '마케팅파트너스', '877-88-17986', '2005-09-11', 123, '0048 행신동', 'Apt. 046', 'C:\upload\logo2.png', 'www.xn---xn--2y5b-9r61bqy2a.co.kr', 'C:\upload\certificate2.png', '탁월한 기술력으로 다양한 산업 분야에 기여하는 기업입니다.', '결혼 및 출산, 육아 지원 프로그램 제공', '개인의 성장을 지원하는 문화', '장지민');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '코어주식회사', '267-72-09714', '2020-12-18', 134, '649 신길면', 'Suite 129', 'C:\upload\logo5.png', 'www.xn---xn--2i4b-9t43bq82f.info', 'C:\upload\certificate3.png', '다양한 배경을 가진 사람들이 협력하여 더 나은 미래를 만들어갑니다.', '사내 도서관과 독서 지원 프로그램 운영', '지속 가능한 발전을 추구하는 문화', '신민서');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '크리에이티브그룹', '284-56-05864', '2017-09-29', 154, '9488 검단읍', 'Suite 339', 'C:\upload\logo2.png', 'www.xn---xn--2x8b-9162b44q.co.kr', 'C:\upload\certificate2.png', '팀워크와 소통을 바탕으로 함께 성장하는 회사입니다.', '결혼 및 출산, 육아 지원 프로그램 제공', '개방적이고 수평적인 조직 문화', '정민서');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '시스템협회', '726-47-38341', '2006-08-31', 112, '36360 신정동', 'Apt. 813', 'C:\upload\logo4.png', 'www.xn---xn--9v2b-9t43bq82f.org', 'C:\upload\certificate1.png', '사회적 책임을 다하며, 글로벌 리더로 성장하는 기업입니다.', '연차 외 특별 휴가 제공', '개인과 팀의 성취를 함께 축하하는 문화', '류현우');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '아이디어기업', '039-71-96377', '2022-12-01', 189, '80906 광명읍', 'Suite 458', 'C:\upload\logo1.png', 'www.xn---xn--vk5b-fm37a087o.info', 'C:\upload\certificate4.png', '고객의 니즈를 충족시키는 서비스 제공을 목표로 합니다.', '연 2회 워크숍과 팀 빌딩 활동', '긍정적이고 즐거운 직장 환경', '최은주');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '스마트글로벌', '578-95-78852', '2010-05-17', 54, '3495 신월면', 'Suite 535', 'C:\upload\logo5.png', 'www.xn---xn--6q8b-f250bs14g.info', 'C:\upload\certificate2.png', '새로운 도전을 통해 글로벌 시장을 선도하는 기업입니다.', '직원 자녀 교육비 지원 및 학자금 대출', '실패를 두려워하지 않고 도전하는 문화', '한서연');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '미래리미티드', '825-73-92225', '2013-12-11', 132, '55019 주안면', 'Apt. 502', 'C:\upload\logo1.png', 'www.xn---xn--2y5b-9r61bc51k.biz', 'C:\upload\certificate5.png', '새로운 도전을 통해 글로벌 시장을 선도하는 기업입니다.', '업무 스트레스 관리를 위한 명상 프로그램 제공', '긍정적이고 즐거운 직장 환경', '류지우');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '디지털인더스트리', '770-41-08461', '2019-07-08', 51, '8442 장유읍', 'Apt. 019', 'C:\upload\logo5.png', 'www.xn---xn--6r5b-9f82biy7g.ne.kr', 'C:\upload\certificate2.png', '기업의 성장이 곧 직원의 성장이라는 믿음을 가진 회사입니다.', '직원들의 복지를 위한 다양한 이벤트와 문화 활동', '자율성과 책임을 중시하는 문화', '오지후');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '액셀러레이터코퍼레이션', '400-21-98986', '2016-09-29', 54, '8248 안양면', 'Apt. 363', 'C:\upload\logo5.png', 'www.xn---xn--vk5b-f923bg72f.info', 'C:\upload\certificate4.png', '사회적 책임을 다하며 지속 가능한 발전을 추구합니다.', '직원 자녀 교육비 지원 및 학자금 대출', '긍정적이고 즐거운 직장 환경', '서지훈');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '솔루션협회', '452-89-10750', '2006-04-13', 115, '1888 중계면', 'Apt. 617', 'C:\upload\logo2.png', 'www.xn---xn--2i4b-9162b44q.com', 'C:\upload\certificate1.png', '고객의 신뢰를 바탕으로 성장을 추구하는 기업입니다.', '직원 자녀 교육비 지원 및 학자금 대출', '다양성을 존중하고 포용하는 문화', '안민재');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '바이오매니지먼트', '359-67-93516', '2011-10-24', 146, '104 신월동', 'Suite 599', 'C:\upload\logo5.png', 'www.xn---xn--vk5b-9t43bh72f.com', 'C:\upload\certificate1.png', '고객의 니즈를 충족시키는 서비스 제공을 목표로 합니다.', '연 2회 워크숍과 팀 빌딩 활동', '적극적인 피드백을 통한 성장 문화', '권우진');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '에너지협회', '574-47-71624', '2005-08-28', 198, '0792 면목읍', 'Suite 053', 'C:\upload\logo1.png', 'www.xn---xn--9v2b-f250bh19f.or.kr', 'C:\upload\certificate2.png', '항상 변화하는 시장에 민첩하게 대응하는 기업입니다.', '자기계발을 위한 교육비 지원', '성과보상제와 자유로운 의견을 교환하는 문화', '안예준');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '프론티어컨설팅', '512-87-42818', '2018-07-21', 26, '210 장유동', 'Suite 048', 'C:\upload\logo4.png', 'www.xn---xn--le5b-9f82bx0r.net', 'C:\upload\certificate4.png', '팀워크와 소통을 바탕으로 함께 성장하는 회사입니다.', '편리한 사내 식사 제공 및 간식 지원', '성과보상제와 자유로운 의견을 교환하는 문화', '권민서');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '에너지기업', '635-62-51789', '2007-09-22', 55, '566 신정읍', 'Apt. 368', 'C:\upload\logo3.png', 'www.xn---xn--vm4b-fm37a087o.org', 'C:\upload\certificate5.png', '사회적 책임을 다하며, 글로벌 리더로 성장하는 기업입니다.', '자기계발을 위한 교육비 지원', '지속 가능한 발전을 추구하는 문화', '김민준');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '에너지테크놀로지', '883-91-27576', '2013-10-24', 57, '2194 창면', 'Suite 753', 'C:\upload\logo2.png', 'www.xn---xn--bh3b-f923bg72f.org', 'C:\upload\certificate5.png', '탁월한 기술력으로 다양한 산업 분야에 기여하는 기업입니다.', '사내 도서관과 독서 지원 프로그램 운영', '직원의 의견을 적극 반영하는 문화', '한현우');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '바이오테크놀로지', '505-41-12441', '2013-01-15', 166, '8380 장유면', 'Suite 623', 'C:\upload\logo4.png', 'www.xn---xn--vv5b-9r61bj49a.biz', 'C:\upload\certificate4.png', '항상 변화하는 시장에 민첩하게 대응하는 기업입니다.', '직원 건강을 위한 헬스케어 프로그램 제공', '팀워크와 협업을 중시하는 문화', '황수빈');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '로지스틱파트너스', '134-87-08587', '2018-10-26', 67, '637 신월읍', 'Suite 504', 'C:\upload\logo2.png', 'www.xn---xn--2x8b-f250bs14g.net', 'C:\upload\certificate1.png', '혁신적인 기술로 내일의 세상을 만듭니다.', '자기계발을 위한 교육비 지원', '직원의 의견을 적극 반영하는 문화', '최민서');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '네트워크인더스트리', '711-19-78431', '2015-10-17', 53, '56189 부평동', 'Suite 258', 'C:\upload\logo2.png', 'www.xn---xn--939a-f250bs14g.com', 'C:\upload\certificate4.png', '직원의 성장과 복지를 최우선으로 생각하는 회사입니다.', '해외 연수 기회와 글로벌 커리어 발전 지원', '직원들의 자율적 리더십을 존중하는 문화', '강지우');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '로지스틱협회', '059-05-86429', '2009-09-24', 197, '543 검단읍', 'Apt. 184', 'C:\upload\logo4.png', 'www.xn---xn--2i4b-fm92b629f.ne.kr', 'C:\upload\certificate4.png', '고객 중심의 사고로 항상 변화하고 발전하는 회사입니다.', '자기계발을 위한 교육비 지원', '실패를 두려워하지 않고 도전하는 문화', '조지후');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '크리에이티브파트너스', '072-51-37284', '2008-03-22', 40, '01175 창동', 'Apt. 599', 'C:\upload\logo2.png', 'www.xn---xn--bh3b-f250bh19f.net', 'C:\upload\certificate2.png', '사회적 책임을 다하며, 글로벌 리더로 성장하는 기업입니다.', '업무 스트레스 관리를 위한 명상 프로그램 제공', '직원들의 자율적 리더십을 존중하는 문화', '오현준');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '이노베이션컨설팅', '457-92-09607', '2023-09-22', 93, '549 주안면', 'Apt. 360', 'C:\upload\logo5.png', 'www.xn---xn--vy8b-fv01bz4x.ne.kr', 'C:\upload\certificate1.png', '고객 중심의 사고로 항상 변화하고 발전하는 회사입니다.', '연 2회 워크숍과 팀 빌딩 활동', '성과보상제와 자유로운 의견을 교환하는 문화', '안서현');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '네트워크주식회사', '761-35-93806', '2008-10-08', 13, '4966 대명면', 'Apt. 471', 'C:\upload\logo4.png', 'www.xn---xn--zv4b-f250bm20f.ne.kr', 'C:\upload\certificate4.png', '고객과의 신뢰를 바탕으로 변화를 선도하는 기업입니다.', '직원 건강을 위한 헬스케어 프로그램 제공', '자율성과 책임을 중시하는 문화', '오서연');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '디지털네트워크', '633-19-67705', '2011-04-29', 134, '01548 검단읍', 'Apt. 178', 'C:\upload\logo2.png', 'www.xn---xn--vy8b-f250bh19f.org', 'C:\upload\certificate1.png', '직원의 성장과 복지를 최우선으로 생각하는 회사입니다.', '연 2회 워크숍과 팀 빌딩 활동', '다양성을 존중하고 포용하는 문화', '윤예은');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '솔루션인더스트리', '574-36-57287', '2012-12-19', 31, '528 상계읍', 'Apt. 594', 'C:\upload\logo1.png', 'www.xn---xn--6r5b-9r61b3x1c.info', 'C:\upload\certificate2.png', '탁월한 기술력으로 다양한 산업 분야에 기여하는 기업입니다.', '매년 건강검진과 정신 건강 지원 프로그램 제공', '적극적인 피드백을 통한 성장 문화', '오예은');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '로지스틱인더스트리', '976-68-11049', '2017-10-09', 189, '33001 주안읍', 'Suite 403', 'C:\upload\logo5.png', 'www.xn---xn--xu5b-9t43bh72f.info', 'C:\upload\certificate2.png', '다양한 배경을 가진 사람들이 협력하여 더 나은 미래를 만들어갑니다.', '자기계발을 위한 교육비 지원', '팀워크와 협업을 중시하는 문화', '최하은');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '스마트벤처', '970-00-82433', '2012-06-08', 126, '763 중계면', 'Apt. 239', 'C:\upload\logo4.png', 'www.xn---xn--vm4b-9t43bh72f.info', 'C:\upload\certificate2.png', '사회적 책임을 다하며 지속 가능한 발전을 추구합니다.', '자기계발을 위한 교육비 지원', '직원의 의견을 적극 반영하는 문화', '한서윤');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '컴플렉스그룹', '269-53-56700', '2017-09-01', 119, '988 신정동', 'Apt. 463', 'C:\upload\logo3.png', 'www.xn---xn--xu5b-f923bg72f.ne.kr', 'C:\upload\certificate3.png', '고객의 니즈를 충족시키는 서비스 제공을 목표로 합니다.', '해외 연수 기회와 글로벌 커리어 발전 지원', '자율성과 책임을 중시하는 문화', '신하은');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '솔루션시스템', '742-76-87610', '2017-11-21', 145, '278 만수면', 'Suite 175', 'C:\upload\logo3.png', 'www.xn---xn--2x8b-9r61bi49a.or.kr', 'C:\upload\certificate2.png', '직원의 성장과 복지를 최우선으로 생각하는 회사입니다.', '업무 스트레스 관리를 위한 명상 프로그램 제공', '자율성과 책임을 중시하는 문화', '송하은');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '이노베이션솔루션', '063-90-36753', '2024-05-20', 150, '732 동탄면', 'Suite 440', 'C:\upload\logo2.png', 'www.xn---xn--4k0b-9r61bqy2a.org', 'C:\upload\certificate2.png', '새로운 도전을 통해 글로벌 시장을 선도하는 기업입니다.', '매년 건강검진과 정신 건강 지원 프로그램 제공', '창의적인 아이디어를 존중하는 문화', '윤지우');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '이노베이션협회', '046-44-92150', '2013-07-16', 146, '8635 광명읍', 'Apt. 297', 'C:\upload\logo3.png', 'www.xn---xn--zf0b-f250bs14g.org', 'C:\upload\certificate5.png', '팀워크와 소통을 바탕으로 함께 성장하는 회사입니다.', '연 2회 워크숍과 팀 빌딩 활동', '자율성과 책임을 중시하는 문화', '오수빈');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '솔루션매니지먼트', '970-16-69969', '2020-06-06', 156, '657 신길면', 'Suite 454', 'C:\upload\logo3.png', 'www.xn---xn--2i4b-fm92bt9i.biz', 'C:\upload\certificate5.png', '혁신적인 아이디어와 뛰어난 기술력으로 글로벌 시장에 도전합니다.', '결혼 및 출산, 육아 지원 프로그램 제공', '창의적인 아이디어를 존중하는 문화', '임서윤');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '크리에이티브컴퍼니', '578-06-84239', '2018-06-27', 150, '65264 만수읍', 'Suite 151', 'C:\upload\logo4.png', 'www.xn---xn--hu5b-fm92b629f.co.kr', 'C:\upload\certificate1.png', '혁신적인 아이디어와 뛰어난 기술력으로 글로벌 시장에 도전합니다.', '해외 연수 기회와 글로벌 커리어 발전 지원', '자율성과 책임을 중시하는 문화', '최서연');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '프론티어그룹', '439-31-33890', '2011-02-12', 109, '20869 광명면', 'Apt. 845', 'C:\upload\logo5.png', 'www.xn---xn--zv4b-9r61bj49a.info', 'C:\upload\certificate3.png', '고객과의 신뢰를 바탕으로 변화를 선도하는 기업입니다.', '업무 스트레스 관리를 위한 명상 프로그램 제공', '적극적인 피드백을 통한 성장 문화', '최윤서');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '로지스틱디벨로퍼', '353-49-49990', '2017-12-07', 135, '8858 신월읍', 'Suite 938', 'C:\upload\logo5.png', 'www.xn---xn--hu5b-f250bm26a.or.kr', 'C:\upload\certificate2.png', '탁월한 기술력으로 다양한 산업 분야에 기여하는 기업입니다.', '연 2회 워크숍과 팀 빌딩 활동', '자율성과 책임을 중시하는 문화', '송예은');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '글로벌파트너스', '688-60-11530', '2012-02-18', 188, '85897 화곡면', 'Apt. 435', 'C:\upload\logo1.png', 'www.xn---xn--xu5b-fm92bt9i.biz', 'C:\upload\certificate5.png', '항상 변화하는 시장에 민첩하게 대응하는 기업입니다.', '직원 자녀 교육비 지원 및 학자금 대출', '팀워크와 협업을 중시하는 문화', '강서윤');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '에너지리미티드', '992-39-94198', '2011-12-06', 110, '3518 주안읍', 'Suite 336', 'C:\upload\logo4.png', 'www.xn---xn--bh3b-9f82biy7g.biz', 'C:\upload\certificate1.png', '다양한 배경을 가진 사람들이 협력하여 더 나은 미래를 만들어갑니다.', '자기계발을 위한 교육비 지원', '지속 가능한 발전을 추구하는 문화', '김예준');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '글로벌인더스트리', '782-75-70156', '2018-02-16', 28, '238 검단읍', 'Apt. 819', 'C:\upload\logo1.png', 'www.xn---xn--vm4b-9r61b3x1c.or.kr', 'C:\upload\certificate2.png', '고객의 니즈를 충족시키는 서비스 제공을 목표로 합니다.', '직원 자녀 교육비 지원 및 학자금 대출', '사회적 책임을 다하는 윤리적 기업 문화', '임민재');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '액셀러레이터인더스트리', '746-35-50708', '2015-04-29', 155, '413 정왕읍', 'Apt. 763', 'C:\upload\logo1.png', 'www.xn---xn--xu5b-9r61bi49a.com', 'C:\upload\certificate4.png', '사회적 책임을 다하며, 글로벌 리더로 성장하는 기업입니다.', '편리한 사내 식사 제공 및 간식 지원', '팀워크와 협업을 중시하는 문화', '홍지훈');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '테크기업', '984-71-97910', '2013-01-23', 175, '4988 방배동', 'Suite 977', 'C:\upload\logo3.png', 'www.xn---xn--2i4b-9162b44q.biz', 'C:\upload\certificate1.png', '탁월한 기술력으로 다양한 산업 분야에 기여하는 기업입니다.', '사내 도서관과 독서 지원 프로그램 운영', '개인과 팀의 성취를 함께 축하하는 문화', '오서현');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '에너지매니지먼트', '133-53-09278', '2023-09-10', 37, '3332 만수읍', 'Apt. 921', 'C:\upload\logo5.png', 'www.xn---xn--vy8b-f250bh19f.biz', 'C:\upload\certificate4.png', '열정과 도전정신으로 새로운 시장을 개척하는 기업입니다.', '자기계발을 위한 교육비 지원', '개방적이고 수평적인 조직 문화', '오민준');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '미래기업', '064-99-89245', '2015-11-22', 118, '88986 동탄동', 'Apt. 931', 'C:\upload\logo3.png', 'www.xn---xn--9v2b-fm37a087o.biz', 'C:\upload\certificate4.png', '사회적 책임을 다하며, 글로벌 리더로 성장하는 기업입니다.', '직원들의 복지를 위한 다양한 이벤트와 문화 활동', '개인의 성장을 지원하는 문화', '임지우');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '시스템컨설팅', '776-97-54294', '2012-10-14', 160, '105 화곡면', 'Apt. 067', 'C:\upload\logo2.png', 'www.xn---xn--xu5b-f250bm20f.biz', 'C:\upload\certificate2.png', '품질과 신뢰를 최우선으로 여기는 회사입니다.', '직원들의 복지를 위한 다양한 이벤트와 문화 활동', '다양성을 존중하고 포용하는 문화', '정민재');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '전략그룹', '848-66-49189', '2010-12-19', 101, '5043 창면', 'Suite 745', 'C:\upload\logo1.png', 'www.xn---xn--zv4b-f250bs14g.ne.kr', 'C:\upload\certificate3.png', '고객의 신뢰를 바탕으로 성장을 추구하는 기업입니다.', '사내 도서관과 독서 지원 프로그램 운영', '다양성을 존중하고 포용하는 문화', '임지우');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '전략디벨로퍼', '011-96-39182', '2009-09-13', 94, '487 검단동', 'Apt. 909', 'C:\upload\logo4.png', 'www.xn---xn--zv4b-f250bm26a.net', 'C:\upload\certificate1.png', '다양한 배경을 가진 사람들이 협력하여 더 나은 미래를 만들어갑니다.', '자유로운 휴가 제도와 유연한 근무시간', '실패를 두려워하지 않고 도전하는 문화', '강준서');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '액셀러레이터그룹', '863-19-77588', '2021-03-10', 56, '35625 연산읍', 'Apt. 278', 'C:\upload\logo3.png', 'www.xn---xn--zv4b-9r61bj49a.ne.kr', 'C:\upload\certificate4.png', '고객의 목소리에 귀 기울여 진정성 있는 서비스를 제공합니다.', '직원 건강을 위한 헬스케어 프로그램 제공', '사회적 책임을 다하는 윤리적 기업 문화', '안지훈');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '솔루션컨설팅', '300-53-35028', '2012-03-24', 16, '884 만수면', 'Apt. 947', 'C:\upload\logo2.png', 'www.xn---xn--vk5b-9f82bx0r.net', 'C:\upload\certificate5.png', '새로운 도전을 통해 글로벌 시장을 선도하는 기업입니다.', '연차 외 특별 휴가 제공', '성과보상제와 자유로운 의견을 교환하는 문화', '한하은');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '네트워크네트웍', '202-38-59484', '2016-07-30', 40, '974 중계읍', 'Apt. 917', 'C:\upload\logo4.png', 'www.xn---xn--o15b-fm92b629f.com', 'C:\upload\certificate4.png', '팀워크와 소통을 바탕으로 함께 성장하는 회사입니다.', '직원 건강을 위한 헬스케어 프로그램 제공', '지속 가능한 발전을 추구하는 문화', '강민서');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '테크인더스트리', '695-23-62900', '2008-06-09', 74, '81353 상면', 'Apt. 960', 'C:\upload\logo5.png', 'www.xn---xn--vv5b-fv01bz4x.co.kr', 'C:\upload\certificate1.png', '고객의 목소리에 귀 기울여 진정성 있는 서비스를 제공합니다.', '연 2회 워크숍과 팀 빌딩 활동', '사회적 책임을 다하는 윤리적 기업 문화', '장현우');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '컴플렉스코퍼레이션', '462-24-91264', '2008-10-02', 39, '555 화곡면', 'Suite 117', 'C:\upload\logo2.png', 'www.xn---xn--bh3b-9f82bnzr.com', 'C:\upload\certificate5.png', '고객의 신뢰를 바탕으로 성장을 추구하는 기업입니다.', '자기계발을 위한 교육비 지원', '창의적인 아이디어를 존중하는 문화', '윤지훈');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '액셀러레이터컨설팅', '127-01-09359', '2010-06-25', 90, '33736 상읍', 'Suite 402', 'C:\upload\logo2.png', 'www.xn---xn--le5b-f250bm20f.ne.kr', 'C:\upload\certificate2.png', '다양한 배경을 가진 사람들이 협력하여 더 나은 미래를 만들어갑니다.', '자유로운 휴가 제도와 유연한 근무시간', '지속 가능한 발전을 추구하는 문화', '이예은');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '미래그룹', '103-94-27019', '2008-05-25', 140, '02638 동탄면', 'Apt. 537', 'C:\upload\logo3.png', 'www.xn---xn--hu5b-fm37a087o.ne.kr', 'C:\upload\certificate2.png', '기업의 성장이 곧 직원의 성장이라는 믿음을 가진 회사입니다.', '직원 자녀 교육비 지원 및 학자금 대출', '창의적인 아이디어를 존중하는 문화', '김예은');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '코어글로벌', '003-35-23492', '2013-09-03', 179, '65043 화곡읍', 'Apt. 334', 'C:\upload\logo5.png', 'www.xn---xn--vv5b-f923bg72f.biz', 'C:\upload\certificate4.png', '지속 가능한 발전을 위해 끊임없이 노력하는 회사입니다.', '업무 스트레스 관리를 위한 명상 프로그램 제공', '긍정적이고 즐거운 직장 환경', '최우진');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '코어홀딩스', '380-81-38161', '2007-02-22', 87, '4330 정왕동', 'Apt. 181', 'C:\upload\logo3.png', 'www.xn---xn--vy8b-9r61bc51k.net', 'C:\upload\certificate2.png', '사회적 책임을 다하며, 글로벌 리더로 성장하는 기업입니다.', '연 2회 워크숍과 팀 빌딩 활동', '지속 가능한 발전을 추구하는 문화', '오서윤');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '에너지홀딩스', '383-78-30343', '2015-11-30', 109, '7225 구로읍', 'Suite 288', 'C:\upload\logo3.png', 'www.xn---xn--939a-9162b44q.com', 'C:\upload\certificate4.png', '지속 가능한 발전을 위해 끊임없이 노력하는 회사입니다.', '연차 외 특별 휴가 제공', '개인의 성장을 지원하는 문화', '한수빈');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '미래파트너스', '038-30-83437', '2007-05-12', 145, '8278 장유면', 'Suite 557', 'C:\upload\logo3.png', 'www.xn---xn--9v2b-9f82bnzr.biz', 'C:\upload\certificate1.png', '창의적이고 혁신적인 아이디어로 미래를 준비하는 기업입니다.', '직원 건강을 위한 헬스케어 프로그램 제공', '다양성을 존중하고 포용하는 문화', '박수빈');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '액셀러레이터랩', '162-34-54849', '2022-09-18', 146, '13273 정왕동', 'Suite 389', 'C:\upload\logo4.png', 'www.xn---xn--o26b-f250bm20f.biz', 'C:\upload\certificate5.png', '혁신적인 기술로 내일의 세상을 만듭니다.', '직원들의 복지를 위한 다양한 이벤트와 문화 활동', '팀워크와 협업을 중시하는 문화', '권현준');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '프론티어컴퍼니', '402-86-01311', '2012-01-09', 27, '2006 광명동', 'Apt. 876', 'C:\upload\logo2.png', 'www.xn---xn--vy8b-f250bm26a.co.kr', 'C:\upload\certificate4.png', '사회적 책임을 다하며, 글로벌 리더로 성장하는 기업입니다.', '업무 스트레스 관리를 위한 명상 프로그램 제공', '적극적인 피드백을 통한 성장 문화', '송건우');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '미래컴퍼니', '554-79-17172', '2021-09-17', 149, '8616 방배읍', 'Apt. 232', 'C:\upload\logo1.png', 'www.xn---xn--vm4b-9t43bq82f.or.kr', 'C:\upload\certificate1.png', '열정과 도전정신으로 새로운 시장을 개척하는 기업입니다.', '탄력적 근무제와 재택 근무 지원', '지속 가능한 발전을 추구하는 문화', '안건우');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '전략기업', '726-60-22140', '2018-05-29', 124, '157 신월읍', 'Suite 700', 'C:\upload\logo3.png', 'www.xn---xn--vm4b-9f82bx0r.org', 'C:\upload\certificate3.png', '지속 가능한 발전을 위해 끊임없이 노력하는 회사입니다.', '직원들의 복지를 위한 다양한 이벤트와 문화 활동', '자율성과 책임을 중시하는 문화', '김서연');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '액셀러레이터인더스트리', '731-36-11764', '2014-10-07', 174, '77205 주안읍', 'Apt. 925', 'C:\upload\logo5.png', 'www.xn---xn--vm4b-f250bs14g.or.kr', 'C:\upload\certificate3.png', '품질과 신뢰를 최우선으로 여기는 회사입니다.', '연 2회 워크숍과 팀 빌딩 활동', '개인과 팀의 성취를 함께 축하하는 문화', '홍수빈');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '마케팅협회', '384-59-34057', '2006-08-05', 13, '339 방배동', 'Suite 490', 'C:\upload\logo3.png', 'www.xn---xn--xu5b-f250bs14g.co.kr', 'C:\upload\certificate2.png', '고객의 신뢰를 바탕으로 성장을 추구하는 기업입니다.', '자기계발을 위한 교육비 지원', '다양성을 존중하고 포용하는 문화', '조지민');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '코어코퍼레이션', '420-71-88941', '2013-07-11', 41, '25208 장유읍', 'Apt. 541', 'C:\upload\logo2.png', 'www.xn---xn--vk5b-9t43bh72f.org', 'C:\upload\certificate3.png', '고객과의 신뢰를 바탕으로 변화를 선도하는 기업입니다.', '직원들의 복지를 위한 다양한 이벤트와 문화 활동', '개방적이고 수평적인 조직 문화', '정윤서');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '글로벌주식회사', '195-66-26261', '2005-11-01', 145, '491 안양읍', 'Apt. 521', 'C:\upload\logo3.png', 'www.xn---xn--vk5b-f250bm20f.biz', 'C:\upload\certificate2.png', '사회적 책임을 다하며 지속 가능한 발전을 추구합니다.', '직원 자녀 교육비 지원 및 학자금 대출', '직원들의 자율적 리더십을 존중하는 문화', '임준서');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '컴플렉스네트웍', '512-17-68211', '2012-12-05', 71, '117 신월면', 'Suite 100', 'C:\upload\logo3.png', 'www.xn---xn--4k0b-9f82bx0r.info', 'C:\upload\certificate2.png', '혁신적인 기술로 내일의 세상을 만듭니다.', '편리한 사내 식사 제공 및 간식 지원', '팀워크와 협업을 중시하는 문화', '이민준');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '디지털파트너스', '863-06-89122', '2020-12-07', 89, '212 광명동', 'Suite 169', 'C:\upload\logo3.png', 'www.xn---xn--2x8b-9t43bh72f.biz', 'C:\upload\certificate4.png', '팀워크와 소통을 바탕으로 함께 성장하는 회사입니다.', '매년 건강검진과 정신 건강 지원 프로그램 제공', '개방적이고 수평적인 조직 문화', '강지우');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '액셀러레이터협회', '619-22-27842', '2016-09-25', 199, '6074 연산면', 'Suite 587', 'C:\upload\logo2.png', 'www.xn---xn--9v2b-9162b44q.biz', 'C:\upload\certificate5.png', '지속 가능한 발전을 위해 끊임없이 노력하는 회사입니다.', '자유로운 휴가 제도와 유연한 근무시간', '다양성을 존중하고 포용하는 문화', '류서현');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '아이디어그룹', '697-17-10659', '2023-05-16', 82, '77958 상도읍', 'Apt. 397', 'C:\upload\logo5.png', 'www.xn---xn--bh3b-f923bg72f.net', 'C:\upload\certificate2.png', '팀워크와 소통을 바탕으로 함께 성장하는 회사입니다.', '탄력적 근무제와 재택 근무 지원', '팀워크와 협업을 중시하는 문화', '이서연');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '액셀러레이터매니지먼트', '728-42-51369', '2005-06-29', 42, '47095 광명동', 'Suite 531', 'C:\upload\logo5.png', 'www.xn---xn--6r5b-f250bm20f.org', 'C:\upload\certificate5.png', '사회적 책임을 다하며, 글로벌 리더로 성장하는 기업입니다.', '자유로운 휴가 제도와 유연한 근무시간', '자율성과 책임을 중시하는 문화', '홍지민');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '테크벤처', '063-45-79164', '2006-02-09', 86, '7995 잠실면', 'Suite 174', 'C:\upload\logo4.png', 'www.xn---xn--vy8b-fm92bt9i.co.kr', 'C:\upload\certificate3.png', '사회적 책임을 다하며, 글로벌 리더로 성장하는 기업입니다.', '연 2회 워크숍과 팀 빌딩 활동', '사회적 책임을 다하는 윤리적 기업 문화', '오은주');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '디지털홀딩스', '568-72-15374', '2008-02-21', 146, '51350 안양면', 'Apt. 547', 'C:\upload\logo1.png', 'www.xn---xn--6q8b-9t43bh72f.co.kr', 'C:\upload\certificate3.png', '고객 중심의 사고로 항상 변화하고 발전하는 회사입니다.', '주택자금 대출 및 임대 지원', '창의적인 아이디어를 존중하는 문화', '한우진');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '테크네트웍', '267-68-60757', '2006-02-20', 116, '7356 시흥동', 'Suite 464', 'C:\upload\logo4.png', 'www.xn---xn--6q8b-fm92b629f.co.kr', 'C:\upload\certificate4.png', '고객 중심의 사고로 항상 변화하고 발전하는 회사입니다.', '직원 건강을 위한 헬스케어 프로그램 제공', '지속 가능한 발전을 추구하는 문화', '강예은');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '프론티어랩', '879-78-48181', '2005-11-08', 174, '025 정왕동', 'Suite 900', 'C:\upload\logo5.png', 'www.xn---xn--2i4b-fm37a087o.com', 'C:\upload\certificate1.png', '혁신적인 아이디어와 뛰어난 기술력으로 글로벌 시장에 도전합니다.', '사내 도서관과 독서 지원 프로그램 운영', '다양성을 존중하고 포용하는 문화', '오현우');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '스마트시스템', '920-32-39221', '2018-04-12', 83, '1948 안양읍', 'Suite 822', 'C:\upload\logo3.png', 'www.xn---xn--bh3b-f250bm20f.ne.kr', 'C:\upload\certificate1.png', '혁신적인 아이디어와 뛰어난 기술력으로 글로벌 시장에 도전합니다.', '주택자금 대출 및 임대 지원', '개방적이고 수평적인 조직 문화', '김서윤');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '프론티어컨설팅', '819-67-84967', '2009-01-07', 105, '94288 연산읍', 'Suite 415', 'C:\upload\logo5.png', 'www.xn---xn--9v2b-9r61b3x1c.net', 'C:\upload\certificate4.png', '고객의 니즈를 충족시키는 서비스 제공을 목표로 합니다.', '결혼 및 출산, 육아 지원 프로그램 제공', '실패를 두려워하지 않고 도전하는 문화', '임하은');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '네트워크컨설팅', '390-92-17575', '2010-10-31', 31, '254 상계동', 'Suite 544', 'C:\upload\logo5.png', 'www.xn---xn--le5b-9r61bc51k.ne.kr', 'C:\upload\certificate4.png', '품질과 신뢰를 최우선으로 여기는 회사입니다.', '연차 외 특별 휴가 제공', '직원들의 자율적 리더십을 존중하는 문화', '최은주');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '테크글로벌', '322-97-48951', '2017-12-27', 103, '2287 창동', 'Suite 181', 'C:\upload\logo3.png', 'www.xn---xn--6q8b-f250bh19f.com', 'C:\upload\certificate1.png', '팀워크와 소통을 바탕으로 함께 성장하는 회사입니다.', '결혼 및 출산, 육아 지원 프로그램 제공', '다양성을 존중하고 포용하는 문화', '조서연');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '스마트시스템', '483-01-16507', '2018-12-17', 15, '336 정왕읍', 'Suite 960', 'C:\upload\logo2.png', 'www.xn---xn--4k0b-9t43bq82f.co.kr', 'C:\upload\certificate1.png', '새로운 도전을 통해 글로벌 시장을 선도하는 기업입니다.', '업무 스트레스 관리를 위한 명상 프로그램 제공', '개인과 팀의 성취를 함께 축하하는 문화', '강하은');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '에너지기업', '981-02-89626', '2022-02-10', 129, '5416 상계읍', 'Suite 431', 'C:\upload\logo1.png', 'www.xn---xn--2x8b-f250bs14g.co.kr', 'C:\upload\certificate3.png', '사회적 책임을 다하며, 글로벌 리더로 성장하는 기업입니다.', '결혼 및 출산, 육아 지원 프로그램 제공', '적극적인 피드백을 통한 성장 문화', '조서연');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '바이오글로벌', '096-59-62603', '2005-05-27', 30, '0633 시흥면', 'Apt. 421', 'C:\upload\logo3.png', 'www.xn---xn--zf0b-9t43bq82f.or.kr', 'C:\upload\certificate4.png', '탁월한 기술력으로 다양한 산업 분야에 기여하는 기업입니다.', '직원 자녀 교육비 지원 및 학자금 대출', '실패를 두려워하지 않고 도전하는 문화', '이예은');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '프론티어리미티드', '425-10-55632', '2023-07-01', 199, '95558 신정읍', 'Apt. 234', 'C:\upload\logo4.png', 'www.xn---xn--2i4b-9f82bnzr.co.kr', 'C:\upload\certificate4.png', '고객의 니즈를 충족시키는 서비스 제공을 목표로 합니다.', '직원 자녀 교육비 지원 및 학자금 대출', '직원의 의견을 적극 반영하는 문화', '송예준');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '로지스틱주식회사', '463-04-27513', '2021-12-01', 161, '4096 중계읍', 'Apt. 773', 'C:\upload\logo1.png', 'www.xn---xn--vv5b-9162bc7f.org', 'C:\upload\certificate2.png', '기업의 성장이 곧 직원의 성장이라는 믿음을 가진 회사입니다.', '업무 스트레스 관리를 위한 명상 프로그램 제공', '직원의 의견을 적극 반영하는 문화', '한지우');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '스마트리미티드', '648-77-26603', '2020-02-15', 90, '07987 면목면', 'Apt. 121', 'C:\upload\logo2.png', 'www.xn---xn--2x8b-fm37a087o.ne.kr', 'C:\upload\certificate2.png', '새로운 도전을 통해 글로벌 시장을 선도하는 기업입니다.', '자유로운 휴가 제도와 유연한 근무시간', '팀워크와 협업을 중시하는 문화', '김민준');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '로지스틱협회', '403-32-35282', '2023-04-09', 30, '8772 부평동', 'Suite 896', 'C:\upload\logo3.png', 'www.xn---xn--le5b-fm92bt9i.ne.kr', 'C:\upload\certificate5.png', '고객의 니즈를 충족시키는 서비스 제공을 목표로 합니다.', '업무 스트레스 관리를 위한 명상 프로그램 제공', '적극적인 피드백을 통한 성장 문화', '한은주');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '네트워크그룹', '617-97-80216', '2020-06-21', 198, '01488 상계읍', 'Suite 000', 'C:\upload\logo1.png', 'www.xn---xn--le5b-9162bc7f.biz', 'C:\upload\certificate3.png', '고객과의 신뢰를 바탕으로 변화를 선도하는 기업입니다.', '편리한 사내 식사 제공 및 간식 지원', '개인의 성장을 지원하는 문화', '장윤서');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '글로벌홀딩스', '886-51-35294', '2009-10-29', 64, '0014 구로동', 'Apt. 716', 'C:\upload\logo2.png', 'www.xn---xn--6q8b-9r61b3x1c.ne.kr', 'C:\upload\certificate2.png', '품질과 신뢰를 최우선으로 여기는 회사입니다.', '편리한 사내 식사 제공 및 간식 지원', '개인과 팀의 성취를 함께 축하하는 문화', '김준서');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '액셀러레이터협회', '896-77-51411', '2022-11-22', 125, '330 장유면', 'Apt. 557', 'C:\upload\logo5.png', 'www.xn---xn--o26b-9f82biy7g.co.kr', 'C:\upload\certificate3.png', '기업의 성장이 곧 직원의 성장이라는 믿음을 가진 회사입니다.', '편리한 사내 식사 제공 및 간식 지원', '자율성과 책임을 중시하는 문화', '강하은');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '코어그룹', '104-82-94544', '2015-02-17', 70, '95466 상도동', 'Apt. 835', 'C:\upload\logo4.png', 'www.xn---xn--vv5b-9r61bj49a.net', 'C:\upload\certificate3.png', '혁신적인 아이디어와 뛰어난 기술력으로 글로벌 시장에 도전합니다.', '편리한 사내 식사 제공 및 간식 지원', '다양성을 존중하고 포용하는 문화', '안민준');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '솔루션컨설팅', '324-00-18770', '2013-09-27', 45, '616 연산읍', 'Suite 007', 'C:\upload\logo3.png', 'www.xn---xn--xu5b-9t43bh72f.com', 'C:\upload\certificate5.png', '열정과 도전정신으로 새로운 시장을 개척하는 기업입니다.', '직원 자녀 교육비 지원 및 학자금 대출', '자율성과 책임을 중시하는 문화', '이준서');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '크리에이티브리미티드', '604-64-48112', '2008-09-13', 104, '91163 신정읍', 'Suite 407', 'C:\upload\logo4.png', 'www.xn---xn--le5b-9r61b3x1c.net', 'C:\upload\certificate2.png', '고객 중심의 사고로 항상 변화하고 발전하는 회사입니다.', '직원 자녀 교육비 지원 및 학자금 대출', '창의적인 아이디어를 존중하는 문화', '장현우');

INSERT INTO TBL_COMPANY
(ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, COMPANY_ESTABLISHMENT, COMPANY_EMPLOYEE, COMPANY_MAIN_ADDRESS, COMPANY_SUB_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO)
VALUES (SEQ_COMPANY.NEXTVAL, '바이오테크놀로지', '728-42-53697', '2006-04-29', 98, '48498 동탄면', 'Suite 613', 'C:\upload\logo5.png', 'www.xn---xn--2x8b-9162b44q.info', 'C:\upload\certificate4.png', '고객의 신뢰를 바탕으로 성장을 추구하는 기업입니다.', '편리한 사내 식사 제공 및 간식 지원', '지속 가능한 발전을 추구하는 문화', '오민재');