INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '이용문의', '문의사항을 빠르게 처리해 주시기 바랍니다.', '처리완료', 69, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '이용문의', '결제 내역 확인을 요청합니다.', '처리완료', 12, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '기타', '회원 등급을 변경하고 싶습니다.', '처리완료', 28, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '계정문의', '문의사항을 빠르게 처리해 주시기 바랍니다.', '처리중', 73, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '오류문의', '새로운 혜택이 적용되지 않았습니다.', '처리중', 46, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '이용문의', '서비스 사용 방법을 알고 싶습니다.', '처리완료', 15, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '오류문의', '결제 내역 확인을 요청합니다.', '처리완료', 100, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '기타', '회원 등급을 변경하고 싶습니다.', '처리완료', 43, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '계정문의', '서비스 이용 시 문제가 발생했습니다.', '처리완료', 67, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '오류문의', '페이지 사용 중 자주 발생하는 오류가 있습니다.', '처리완료', 21, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '이용문의', '가입 시 입력한 정보를 수정하고 싶습니다.', '처리완료', 23, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '이용문의', '결제 내역 확인을 요청합니다.', '처리중', 44, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '오류문의', '서비스 사용 방법을 알고 싶습니다.', '처리중', 6, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '기타', '회원 탈퇴를 하고 싶습니다.', '처리중', 64, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '기타', '문의사항을 빠르게 처리해 주시기 바랍니다.', '처리완료', 44, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '기타', '비밀번호를 변경하고 싶습니다.', '처리완료', 16, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '계정문의', '프로그램 신청 취소를 요청합니다.', '처리완료', 54, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '기타', '이메일 인증이 되지 않습니다.', '처리중', 50, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '계정문의', '서비스 사용 방법을 알고 싶습니다.', '처리중', 33, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '오류문의', '회원정보 수정이 필요합니다.', '처리완료', 47, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '기타', '문의사항을 빠르게 처리해 주시기 바랍니다.', '처리중', 77, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '계정문의', '서비스 이용 시 문제가 발생했습니다.', '처리중', 26, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '오류문의', '이메일 인증이 되지 않습니다.', '처리중', 69, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '오류문의', '카카오 인증이 정상적으로 작동하지 않습니다.', '처리완료', 68, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '이용문의', '회원 등급을 변경하고 싶습니다.', '처리중', 86, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '계정문의', '최근 로그인 기록을 확인하고 싶습니다.', '처리완료', 78, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '이용문의', '회원 탈퇴를 하고 싶습니다.', '처리중', 65, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '이용문의', '이메일 인증이 되지 않습니다.', '처리중', 48, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '계정문의', '문의사항을 빠르게 처리해 주시기 바랍니다.', '처리중', 52, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '기타', '프로그램 신청 취소를 요청합니다.', '처리중', 89, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '계정문의', '새로운 혜택이 적용되지 않았습니다.', '처리완료', 29, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '계정문의', '회원정보 수정이 필요합니다.', '처리중', 26, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '이용문의', '페이지 사용 중 자주 발생하는 오류가 있습니다.', '처리완료', 28, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '오류문의', '회원 탈퇴를 하고 싶습니다.', '처리중', 54, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '기타', '카카오 인증이 정상적으로 작동하지 않습니다.', '처리중', 27, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '이용문의', '회원 등급을 변경하고 싶습니다.', '처리중', 100, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '기타', '최근 로그인 기록을 확인하고 싶습니다.', '처리중', 94, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '오류문의', '회원 탈퇴를 하고 싶습니다.', '처리중', 98, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '오류문의', '새로운 혜택이 적용되지 않았습니다.', '처리중', 34, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '오류문의', '결제 내역 확인을 요청합니다.', '처리완료', 86, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '계정문의', '프로그램 신청 취소를 요청합니다.', '처리중', 87, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '기타', '회원 탈퇴를 하고 싶습니다.', '처리중', 45, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '이용문의', '최근 로그인 기록을 확인하고 싶습니다.', '처리중', 55, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '계정문의', '결제 내역 확인을 요청합니다.', '처리완료', 82, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '기타', '회원정보 수정이 필요합니다.', '처리완료', 54, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '이용문의', '결제 내역 확인을 요청합니다.', '처리중', 49, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '계정문의', '이메일 인증이 되지 않습니다.', '처리중', 38, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '오류문의', '최근 로그인 기록을 확인하고 싶습니다.', '처리중', 14, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '이용문의', '회원 탈퇴를 하고 싶습니다.', '처리중', 3, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '오류문의', '회원 탈퇴를 하고 싶습니다.', '처리완료', 89, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '기타', '회원 탈퇴를 하고 싶습니다.', '처리중', 6, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '계정문의', '이메일 인증이 되지 않습니다.', '처리완료', 88, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '계정문의', '서비스 사용 방법을 알고 싶습니다.', '처리완료', 86, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '기타', '결제 내역 확인을 요청합니다.', '처리완료', 54, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '오류문의', '비밀번호를 변경하고 싶습니다.', '처리중', 55, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '기타', '서비스 이용 시 문제가 발생했습니다.', '처리완료', 40, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '오류문의', '서비스 이용 시 문제가 발생했습니다.', '처리중', 12, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '이용문의', '비밀번호를 변경하고 싶습니다.', '처리중', 60, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '기타', '가입 시 입력한 정보를 수정하고 싶습니다.', '처리중', 22, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '오류문의', '새로운 혜택이 적용되지 않았습니다.', '처리중', 23, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '기타', '이메일 인증이 되지 않습니다.', '처리완료', 70, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '계정문의', '회원정보 수정이 필요합니다.', '처리완료', 60, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '오류문의', '프로그램 신청 취소를 요청합니다.', '처리중', 28, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '계정문의', '페이지 사용 중 자주 발생하는 오류가 있습니다.', '처리완료', 81, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '오류문의', '회원정보 수정이 필요합니다.', '처리완료', 70, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '계정문의', '회원정보 수정이 필요합니다.', '처리중', 34, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '기타', '회원 등급을 변경하고 싶습니다.', '처리완료', 29, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '계정문의', '회원정보 수정이 필요합니다.', '처리완료', 43, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '오류문의', '이메일 인증이 되지 않습니다.', '처리중', 72, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '계정문의', '새로운 혜택이 적용되지 않았습니다.', '처리완료', 64, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '이용문의', '페이지 사용 중 자주 발생하는 오류가 있습니다.', '처리중', 98, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '오류문의', '서비스 이용 시 문제가 발생했습니다.', '처리완료', 60, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '오류문의', '회원정보 수정이 필요합니다.', '처리완료', 86, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '계정문의', '서비스 사용 방법을 알고 싶습니다.', '처리중', 64, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '이용문의', '이메일 인증이 되지 않습니다.', '처리완료', 78, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '기타', '회원정보 수정이 필요합니다.', '처리중', 95, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '이용문의', '회원 등급을 변경하고 싶습니다.', '처리완료', 37, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '기타', '가입 시 입력한 정보를 수정하고 싶습니다.', '처리중', 18, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '이용문의', '회원 등급을 변경하고 싶습니다.', '처리완료', 43, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '계정문의', '최근 로그인 기록을 확인하고 싶습니다.', '처리완료', 38, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '오류문의', '카카오 인증이 정상적으로 작동하지 않습니다.', '처리중', 34, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '계정문의', '서비스 사용 방법을 알고 싶습니다.', '처리완료', 6, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '이용문의', '이메일 인증이 되지 않습니다.', '처리중', 89, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '오류문의', '서비스 사용 방법을 알고 싶습니다.', '처리완료', 4, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '기타', '프로그램 신청 취소를 요청합니다.', '처리완료', 54, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '오류문의', '카카오 인증이 정상적으로 작동하지 않습니다.', '처리중', 17, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '이용문의', '페이지 사용 중 자주 발생하는 오류가 있습니다.', '처리완료', 33, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '이용문의', '비밀번호를 변경하고 싶습니다.', '처리중', 35, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '오류문의', '회원정보 수정이 필요합니다.', '처리완료', 16, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '오류문의', '회원 탈퇴를 하고 싶습니다.', '처리중', 56, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '기타', '문의사항을 빠르게 처리해 주시기 바랍니다.', '처리중', 54, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '기타', '회원 탈퇴를 하고 싶습니다.', '처리중', 34, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '계정문의', '프로그램 신청 취소를 요청합니다.', '처리완료', 86, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '기타', '이메일 인증이 되지 않습니다.', '처리중', 98, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '이용문의', '서비스 사용 방법을 알고 싶습니다.', '처리완료', 62, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '기타', '페이지 사용 중 자주 발생하는 오류가 있습니다.', '처리완료', 6, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '기타', '결제 내역 확인을 요청합니다.', '처리완료', 47, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '이용문의', '서비스 사용 방법을 알고 싶습니다.', '처리중', 37, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '기타', '가입 시 입력한 정보를 수정하고 싶습니다.', '처리완료', 97, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER_INQUIRY
(ID, MEMBER_INQUIRY_TYPE, MEMBER_INQUIRY_DETAIL, MEMBER_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_MEMBER_INQUIRY.NEXTVAL, '기타', '회원정보 수정이 필요합니다.', '처리완료', 28, SYSDATE, SYSDATE);