INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '정지훈', '010-4485-3632', 'ypouzs@example.com', 'C:\upload\image3.png', '일반', 0, '활성', '1997-02-27', TO_TIMESTAMP('2025-01-05 03:04:53', 'YYYY-MM-DD HH24:MI:SS'));


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '안은주', '010-8052-5066', 'ewroik@example.com', 'C:\upload\image5.png', '일반', 0, '활성', '1985-03-11', TO_TIMESTAMP('2024-10-27 01:58:04', 'YYYY-MM-DD HH24:MI:SS'));


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '정지우', '010-7912-7696', 'qrilcq@example.com', 'C:\upload\image4.png', '일반', 0, '활성', '1993-02-26', TO_TIMESTAMP('2025-03-07 01:21:38', 'YYYY-MM-DD HH24:MI:SS'));


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '박민준', '010-4936-5734', 'qquaid@example.com', 'C:\upload\image5.png', '일반', 0, '활성', '1993-02-11', TO_TIMESTAMP('2025-01-13 16:55:51', 'YYYY-MM-DD HH24:MI:SS'));


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '권민서', '010-2648-9586', 'dllvof@example.com', 'C:\upload\image2.png', '일반', 0, '활성', '1994-12-17', TO_TIMESTAMP('2024-10-30 23:21:20', 'YYYY-MM-DD HH24:MI:SS'));


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '류준서', '010-1337-7712', 'gvwbhc@example.com', 'C:\upload\image4.png', '일반', 0, '활성', '1992-09-28', TO_TIMESTAMP('2024-12-18 23:32:47', 'YYYY-MM-DD HH24:MI:SS'));


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '권지우', '010-1743-8547', 'ytswzq@example.com', 'C:\upload\image1.png', '일반', 0, '활성', '1989-01-03', TO_TIMESTAMP('2024-10-11 01:42:42', 'YYYY-MM-DD HH24:MI:SS'));


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '한윤서', '010-5461-3761', 'czkmsy@example.com', 'C:\upload\image2.png', '기업', 0, '활성', '1992-06-26', TO_TIMESTAMP('2024-10-26 18:58:23', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO TBL_COMPANY_MEMBER
(ID, COMPANY_ID, COMPANY_MEMBER_POSITION, COMPANY_MEMBER_AUTHORITY, COMPANY_MEMBER_DEPARTMENT)
VALUES (8, 26, '팀장', '관리자', '전산부');


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '오은주', '010-9402-8978', 'qmwucf@example.com', 'C:\upload\image4.png', '기업', 0, '활성', '1998-06-10', TO_TIMESTAMP('2024-10-23 02:23:10', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO TBL_COMPANY_MEMBER
(ID, COMPANY_ID, COMPANY_MEMBER_POSITION, COMPANY_MEMBER_AUTHORITY, COMPANY_MEMBER_DEPARTMENT)
VALUES (9, 89, '인턴', '관리자', '마케팅부');


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '최건우', '010-7315-3295', 'mlxphs@example.com', 'C:\upload\image5.png', '기업', 0, '활성', '1986-12-17', TO_TIMESTAMP('2024-12-19 07:14:52', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO TBL_COMPANY_MEMBER
(ID, COMPANY_ID, COMPANY_MEMBER_POSITION, COMPANY_MEMBER_AUTHORITY, COMPANY_MEMBER_DEPARTMENT)
VALUES (10, 84, '사원', '관리자', '재무부');


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '박현준', '010-2065-8485', 'mfhirg@example.com', 'C:\upload\image2.png', '기업', 0, '활성', '1993-11-21', TO_TIMESTAMP('2024-12-14 18:20:18', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO TBL_COMPANY_MEMBER
(ID, COMPANY_ID, COMPANY_MEMBER_POSITION, COMPANY_MEMBER_AUTHORITY, COMPANY_MEMBER_DEPARTMENT)
VALUES (11, 2, '인턴', '뷰어', '마케팅부');


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '송은주', '010-9688-3564', 'rhgjbk@example.com', 'C:\upload\image2.png', '일반', 0, '활성', '1999-06-07', TO_TIMESTAMP('2025-01-30 08:13:18', 'YYYY-MM-DD HH24:MI:SS'));


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '신현준', '010-6513-5571', 'tzbbld@example.com', 'C:\upload\image2.png', '기업', 0, '활성', '1991-09-09', TO_TIMESTAMP('2025-01-08 18:37:47', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO TBL_COMPANY_MEMBER
(ID, COMPANY_ID, COMPANY_MEMBER_POSITION, COMPANY_MEMBER_AUTHORITY, COMPANY_MEMBER_DEPARTMENT)
VALUES (13, 23, '사원', '관리자', '마케팅부');


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '송지민', '010-5581-3141', 'bgqpdl@example.com', 'C:\upload\image2.png', '일반', 0, '활성', '1985-06-08', TO_TIMESTAMP('2025-02-25 15:16:52', 'YYYY-MM-DD HH24:MI:SS'));


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '최지후', '010-2298-5769', 'kreetn@example.com', 'C:\upload\image1.png', '일반', 0, '활성', '1987-11-25', TO_TIMESTAMP('2025-02-15 08:48:24', 'YYYY-MM-DD HH24:MI:SS'));


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '황하은', '010-6969-7309', 'pzkyqb@example.com', 'C:\upload\image2.png', '기업', 0, '활성', '1985-03-13', TO_TIMESTAMP('2025-02-27 12:20:02', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO TBL_COMPANY_MEMBER
(ID, COMPANY_ID, COMPANY_MEMBER_POSITION, COMPANY_MEMBER_AUTHORITY, COMPANY_MEMBER_DEPARTMENT)
VALUES (16, 64, '사원', '뷰어', '재무부');


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '이현준', '010-2836-8603', 'olrwna@example.com', 'C:\upload\image3.png', '기업', 0, '활성', '1998-03-21', TO_TIMESTAMP('2024-12-28 09:15:25', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO TBL_COMPANY_MEMBER
(ID, COMPANY_ID, COMPANY_MEMBER_POSITION, COMPANY_MEMBER_AUTHORITY, COMPANY_MEMBER_DEPARTMENT)
VALUES (17, 97, '인턴', '관리자', '영업부');


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '장윤서', '010-6263-2536', 'emctvi@example.com', 'C:\upload\image5.png', '기업', 0, '활성', '1998-01-18', TO_TIMESTAMP('2025-03-18 23:00:20', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO TBL_COMPANY_MEMBER
(ID, COMPANY_ID, COMPANY_MEMBER_POSITION, COMPANY_MEMBER_AUTHORITY, COMPANY_MEMBER_DEPARTMENT)
VALUES (18, 84, '팀장', '관리자', '전산부');


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '김준서', '010-6297-4155', 'izqout@example.com', 'C:\upload\image5.png', '일반', 0, '활성', '2000-03-17', TO_TIMESTAMP('2024-11-25 06:24:46', 'YYYY-MM-DD HH24:MI:SS'));


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '이현우', '010-1621-7070', 'wwgbwu@example.com', 'C:\upload\image3.png', '기업', 0, '활성', '1992-04-06', TO_TIMESTAMP('2025-02-14 07:32:32', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO TBL_COMPANY_MEMBER
(ID, COMPANY_ID, COMPANY_MEMBER_POSITION, COMPANY_MEMBER_AUTHORITY, COMPANY_MEMBER_DEPARTMENT)
VALUES (20, 64, '인턴', '관리자', '인사부');


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '송하은', '010-9279-7980', 'uummbm@example.com', 'C:\upload\image1.png', '기업', 0, '활성', '1994-02-03', TO_TIMESTAMP('2024-11-07 15:07:47', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO TBL_COMPANY_MEMBER
(ID, COMPANY_ID, COMPANY_MEMBER_POSITION, COMPANY_MEMBER_AUTHORITY, COMPANY_MEMBER_DEPARTMENT)
VALUES (21, 42, '대리', '뷰어', '인사부');


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '오지훈', '010-4157-4280', 'epjzrv@example.com', 'C:\upload\image3.png', '일반', 0, '활성', '1994-05-09', TO_TIMESTAMP('2025-01-08 00:26:54', 'YYYY-MM-DD HH24:MI:SS'));


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '임현우', '010-1677-9537', 'ghljcu@example.com', 'C:\upload\image1.png', '기업', 0, '활성', '1998-01-14', TO_TIMESTAMP('2025-01-09 14:52:01', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO TBL_COMPANY_MEMBER
(ID, COMPANY_ID, COMPANY_MEMBER_POSITION, COMPANY_MEMBER_AUTHORITY, COMPANY_MEMBER_DEPARTMENT)
VALUES (23, 44, '인턴', '뷰어', '영업부');


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '홍윤서', '010-4931-1181', 'ewfpar@example.com', 'C:\upload\image5.png', '일반', 0, '활성', '2000-05-21', TO_TIMESTAMP('2025-02-21 19:27:32', 'YYYY-MM-DD HH24:MI:SS'));


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '강윤서', '010-7777-8902', 'rifapn@example.com', 'C:\upload\image4.png', '일반', 0, '활성', '1993-10-21', TO_TIMESTAMP('2024-10-16 07:37:33', 'YYYY-MM-DD HH24:MI:SS'));


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '홍수빈', '010-2193-1784', 'xhoyvt@example.com', 'C:\upload\image5.png', '기업', 0, '활성', '1987-08-25', TO_TIMESTAMP('2024-11-05 03:58:29', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO TBL_COMPANY_MEMBER
(ID, COMPANY_ID, COMPANY_MEMBER_POSITION, COMPANY_MEMBER_AUTHORITY, COMPANY_MEMBER_DEPARTMENT)
VALUES (26, 9, '팀장', '뷰어', '마케팅부');


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '신민서', '010-2632-3956', 'yugmff@example.com', 'C:\upload\image3.png', '일반', 0, '활성', '1988-11-17', TO_TIMESTAMP('2024-12-21 11:47:14', 'YYYY-MM-DD HH24:MI:SS'));


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '이예은', '010-3487-4068', 'fqfrkv@example.com', 'C:\upload\image5.png', '기업', 0, '활성', '1996-12-18', TO_TIMESTAMP('2024-11-03 16:36:19', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO TBL_COMPANY_MEMBER
(ID, COMPANY_ID, COMPANY_MEMBER_POSITION, COMPANY_MEMBER_AUTHORITY, COMPANY_MEMBER_DEPARTMENT)
VALUES (28, 27, '팀장', '관리자', '영업부');


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '신지민', '010-2174-9728', 'pndblw@example.com', 'C:\upload\image4.png', '기업', 0, '활성', '1992-06-12', TO_TIMESTAMP('2024-12-04 08:27:12', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO TBL_COMPANY_MEMBER
(ID, COMPANY_ID, COMPANY_MEMBER_POSITION, COMPANY_MEMBER_AUTHORITY, COMPANY_MEMBER_DEPARTMENT)
VALUES (29, 98, '팀장', '뷰어', '전산부');


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '최현우', '010-5345-1300', 'aeqmze@example.com', 'C:\upload\image2.png', '기업', 0, '활성', '1989-12-04', TO_TIMESTAMP('2025-03-14 21:30:15', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO TBL_COMPANY_MEMBER
(ID, COMPANY_ID, COMPANY_MEMBER_POSITION, COMPANY_MEMBER_AUTHORITY, COMPANY_MEMBER_DEPARTMENT)
VALUES (30, 29, '팀장', '뷰어', '영업부');


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '이서연', '010-8292-5480', 'cotaee@example.com', 'C:\upload\image2.png', '일반', 0, '활성', '2000-04-01', TO_TIMESTAMP('2025-03-01 00:51:07', 'YYYY-MM-DD HH24:MI:SS'));


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '오민서', '010-8042-7855', 'xhglrw@example.com', 'C:\upload\image4.png', '기업', 0, '활성', '1989-02-07', TO_TIMESTAMP('2025-02-12 19:32:40', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO TBL_COMPANY_MEMBER
(ID, COMPANY_ID, COMPANY_MEMBER_POSITION, COMPANY_MEMBER_AUTHORITY, COMPANY_MEMBER_DEPARTMENT)
VALUES (32, 92, '인턴', '뷰어', '전산부');


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '최현우', '010-3316-1943', 'evoidr@example.com', 'C:\upload\image4.png', '일반', 0, '활성', '1995-11-21', TO_TIMESTAMP('2025-03-22 18:09:31', 'YYYY-MM-DD HH24:MI:SS'));


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '정지훈', '010-4615-9004', 'phmxns@example.com', 'C:\upload\image3.png', '기업', 0, '활성', '1990-01-01', TO_TIMESTAMP('2024-11-08 03:00:16', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO TBL_COMPANY_MEMBER
(ID, COMPANY_ID, COMPANY_MEMBER_POSITION, COMPANY_MEMBER_AUTHORITY, COMPANY_MEMBER_DEPARTMENT)
VALUES (34, 88, '팀장', '관리자', '재무부');


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '서수빈', '010-6225-2182', 'payqdy@example.com', 'C:\upload\image4.png', '일반', 0, '활성', '1994-01-24', TO_TIMESTAMP('2024-09-30 15:25:18', 'YYYY-MM-DD HH24:MI:SS'));


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '최우진', '010-9744-9306', 'fuvvzo@example.com', 'C:\upload\image3.png', '일반', 0, '활성', '1993-11-03', TO_TIMESTAMP('2024-12-27 03:46:26', 'YYYY-MM-DD HH24:MI:SS'));


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '한민재', '010-1562-4761', 'yeppbz@example.com', 'C:\upload\image1.png', '기업', 0, '활성', '1995-04-03', TO_TIMESTAMP('2025-01-22 12:25:01', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO TBL_COMPANY_MEMBER
(ID, COMPANY_ID, COMPANY_MEMBER_POSITION, COMPANY_MEMBER_AUTHORITY, COMPANY_MEMBER_DEPARTMENT)
VALUES (37, 61, '사원', '관리자', '재무부');


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '한준서', '010-5213-3704', 'inwzrx@example.com', 'C:\upload\image5.png', '기업', 0, '활성', '2001-05-13', TO_TIMESTAMP('2024-11-11 04:14:45', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO TBL_COMPANY_MEMBER
(ID, COMPANY_ID, COMPANY_MEMBER_POSITION, COMPANY_MEMBER_AUTHORITY, COMPANY_MEMBER_DEPARTMENT)
VALUES (38, 86, '사원', '관리자', '전산부');


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '장지훈', '010-8763-7842', 'otmrkn@example.com', 'C:\upload\image2.png', '일반', 0, '활성', '1987-10-25', TO_TIMESTAMP('2025-03-20 04:30:32', 'YYYY-MM-DD HH24:MI:SS'));


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '황예은', '010-5432-1928', 'ydbrun@example.com', 'C:\upload\image1.png', '기업', 0, '활성', '1994-02-02', TO_TIMESTAMP('2025-03-02 11:01:45', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO TBL_COMPANY_MEMBER
(ID, COMPANY_ID, COMPANY_MEMBER_POSITION, COMPANY_MEMBER_AUTHORITY, COMPANY_MEMBER_DEPARTMENT)
VALUES (40, 100, '인턴', '뷰어', '마케팅부');


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '김은주', '010-9610-4136', 'otfhio@example.com', 'C:\upload\image5.png', '일반', 0, '활성', '1996-05-22', TO_TIMESTAMP('2024-12-25 17:17:30', 'YYYY-MM-DD HH24:MI:SS'));


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '안서윤', '010-8193-9199', 'qlwkjk@example.com', 'C:\upload\image5.png', '일반', 0, '활성', '1994-05-04', TO_TIMESTAMP('2024-10-01 07:32:22', 'YYYY-MM-DD HH24:MI:SS'));


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '신수빈', '010-3421-6038', 'ygwxae@example.com', 'C:\upload\image5.png', '일반', 0, '활성', '1987-03-01', TO_TIMESTAMP('2025-02-17 10:09:16', 'YYYY-MM-DD HH24:MI:SS'));


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '임예준', '010-5768-6863', 'tmbfqq@example.com', 'C:\upload\image1.png', '일반', 0, '활성', '1996-06-09', TO_TIMESTAMP('2024-11-16 19:31:59', 'YYYY-MM-DD HH24:MI:SS'));


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '서예은', '010-3911-6334', 'pfsgjw@example.com', 'C:\upload\image5.png', '기업', 0, '활성', '1988-07-10', TO_TIMESTAMP('2025-02-25 14:37:04', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO TBL_COMPANY_MEMBER
(ID, COMPANY_ID, COMPANY_MEMBER_POSITION, COMPANY_MEMBER_AUTHORITY, COMPANY_MEMBER_DEPARTMENT)
VALUES (45, 42, '인턴', '관리자', '인사부');


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '안지후', '010-8920-1093', 'ospqde@example.com', 'C:\upload\image4.png', '일반', 0, '활성', '1989-05-10', TO_TIMESTAMP('2024-12-09 16:17:13', 'YYYY-MM-DD HH24:MI:SS'));


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '윤서현', '010-4986-2042', 'cisnpf@example.com', 'C:\upload\image5.png', '기업', 0, '활성', '2000-08-13', TO_TIMESTAMP('2024-10-10 07:20:03', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO TBL_COMPANY_MEMBER
(ID, COMPANY_ID, COMPANY_MEMBER_POSITION, COMPANY_MEMBER_AUTHORITY, COMPANY_MEMBER_DEPARTMENT)
VALUES (47, 22, '인턴', '뷰어', '재무부');


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '윤민재', '010-9417-2392', 'kftdyl@example.com', 'C:\upload\image1.png', '기업', 0, '활성', '1985-04-09', TO_TIMESTAMP('2025-03-05 04:34:31', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO TBL_COMPANY_MEMBER
(ID, COMPANY_ID, COMPANY_MEMBER_POSITION, COMPANY_MEMBER_AUTHORITY, COMPANY_MEMBER_DEPARTMENT)
VALUES (48, 29, '사원', '뷰어', '전산부');


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '장서현', '010-3748-9112', 'onuocv@example.com', 'C:\upload\image2.png', '일반', 0, '활성', '1987-04-05', TO_TIMESTAMP('2024-12-10 01:28:43', 'YYYY-MM-DD HH24:MI:SS'));


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '정하은', '010-2271-8891', 'ooktgj@example.com', 'C:\upload\image4.png', '기업', 0, '활성', '1995-01-19', TO_TIMESTAMP('2024-12-20 02:13:31', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO TBL_COMPANY_MEMBER
(ID, COMPANY_ID, COMPANY_MEMBER_POSITION, COMPANY_MEMBER_AUTHORITY, COMPANY_MEMBER_DEPARTMENT)
VALUES (50, 29, '인턴', '뷰어', '전산부');


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '조서현', '010-5067-6249', 'xzdsce@example.com', 'C:\upload\image3.png', '기업', 0, '활성', '1989-09-19', TO_TIMESTAMP('2025-01-10 15:45:51', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO TBL_COMPANY_MEMBER
(ID, COMPANY_ID, COMPANY_MEMBER_POSITION, COMPANY_MEMBER_AUTHORITY, COMPANY_MEMBER_DEPARTMENT)
VALUES (51, 24, '사원', '관리자', '인사부');


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '최지후', '010-4310-1422', 'katqaw@example.com', 'C:\upload\image3.png', '기업', 0, '활성', '2000-07-02', TO_TIMESTAMP('2025-01-16 22:51:32', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO TBL_COMPANY_MEMBER
(ID, COMPANY_ID, COMPANY_MEMBER_POSITION, COMPANY_MEMBER_AUTHORITY, COMPANY_MEMBER_DEPARTMENT)
VALUES (52, 10, '사원', '관리자', '전산부');


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '신민준', '010-7865-4340', 'fonmuq@example.com', 'C:\upload\image4.png', '기업', 0, '활성', '2001-10-10', TO_TIMESTAMP('2025-02-22 08:07:09', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO TBL_COMPANY_MEMBER
(ID, COMPANY_ID, COMPANY_MEMBER_POSITION, COMPANY_MEMBER_AUTHORITY, COMPANY_MEMBER_DEPARTMENT)
VALUES (53, 66, '팀장', '관리자', '영업부');


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '서지민', '010-4961-8194', 'fshvha@example.com', 'C:\upload\image3.png', '기업', 0, '활성', '2001-09-06', TO_TIMESTAMP('2025-03-07 04:24:51', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO TBL_COMPANY_MEMBER
(ID, COMPANY_ID, COMPANY_MEMBER_POSITION, COMPANY_MEMBER_AUTHORITY, COMPANY_MEMBER_DEPARTMENT)
VALUES (54, 9, '팀장', '관리자', '전산부');


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '이지후', '010-9905-4204', 'blgoms@example.com', 'C:\upload\image1.png', '기업', 0, '활성', '1996-08-02', TO_TIMESTAMP('2025-03-05 19:18:31', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO TBL_COMPANY_MEMBER
(ID, COMPANY_ID, COMPANY_MEMBER_POSITION, COMPANY_MEMBER_AUTHORITY, COMPANY_MEMBER_DEPARTMENT)
VALUES (55, 84, '팀장', '관리자', '영업부');


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '조우진', '010-6220-4474', 'bgovsh@example.com', 'C:\upload\image2.png', '일반', 0, '활성', '1998-07-24', TO_TIMESTAMP('2024-10-08 16:07:59', 'YYYY-MM-DD HH24:MI:SS'));


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '박민준', '010-2302-1641', 'lefpro@example.com', 'C:\upload\image4.png', '기업', 0, '활성', '1997-10-25', TO_TIMESTAMP('2024-10-26 01:26:30', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO TBL_COMPANY_MEMBER
(ID, COMPANY_ID, COMPANY_MEMBER_POSITION, COMPANY_MEMBER_AUTHORITY, COMPANY_MEMBER_DEPARTMENT)
VALUES (57, 68, '팀장', '뷰어', '영업부');


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '장은주', '010-6640-3149', 'noqbnu@example.com', 'C:\upload\image5.png', '일반', 0, '활성', '1992-03-04', TO_TIMESTAMP('2024-11-27 07:39:33', 'YYYY-MM-DD HH24:MI:SS'));


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '윤서윤', '010-3402-6275', 'aauthm@example.com', 'C:\upload\image1.png', '기업', 0, '활성', '1999-08-09', TO_TIMESTAMP('2025-01-05 23:30:05', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO TBL_COMPANY_MEMBER
(ID, COMPANY_ID, COMPANY_MEMBER_POSITION, COMPANY_MEMBER_AUTHORITY, COMPANY_MEMBER_DEPARTMENT)
VALUES (59, 96, '팀장', '뷰어', '전산부');


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '오현준', '010-8017-7843', 'jzynoy@example.com', 'C:\upload\image1.png', '기업', 0, '활성', '1988-05-15', TO_TIMESTAMP('2025-03-19 16:41:04', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO TBL_COMPANY_MEMBER
(ID, COMPANY_ID, COMPANY_MEMBER_POSITION, COMPANY_MEMBER_AUTHORITY, COMPANY_MEMBER_DEPARTMENT)
VALUES (60, 72, '대리', '관리자', '마케팅부');


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '윤현우', '010-9596-2802', 'zyuhoj@example.com', 'C:\upload\image3.png', '일반', 0, '활성', '1996-10-28', TO_TIMESTAMP('2024-12-13 15:45:37', 'YYYY-MM-DD HH24:MI:SS'));


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '김건우', '010-4306-5347', 'yqytey@example.com', 'C:\upload\image5.png', '일반', 0, '활성', '1999-05-19', TO_TIMESTAMP('2024-12-22 17:22:47', 'YYYY-MM-DD HH24:MI:SS'));


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '정건우', '010-3332-6986', 'wldrfb@example.com', 'C:\upload\image5.png', '일반', 0, '활성', '2000-06-11', TO_TIMESTAMP('2025-02-13 07:35:22', 'YYYY-MM-DD HH24:MI:SS'));


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '서민준', '010-3610-2018', 'oxtkpi@example.com', 'C:\upload\image5.png', '기업', 0, '활성', '1997-06-11', TO_TIMESTAMP('2025-03-17 20:52:25', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO TBL_COMPANY_MEMBER
(ID, COMPANY_ID, COMPANY_MEMBER_POSITION, COMPANY_MEMBER_AUTHORITY, COMPANY_MEMBER_DEPARTMENT)
VALUES (64, 88, '사원', '관리자', '인사부');


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '오민재', '010-9694-2858', 'ikxkpj@example.com', 'C:\upload\image2.png', '일반', 0, '활성', '1995-04-02', TO_TIMESTAMP('2025-03-23 17:31:19', 'YYYY-MM-DD HH24:MI:SS'));


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '정예은', '010-5362-8020', 'gvncyq@example.com', 'C:\upload\image2.png', '기업', 0, '활성', '1995-09-16', TO_TIMESTAMP('2024-09-28 05:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO TBL_COMPANY_MEMBER
(ID, COMPANY_ID, COMPANY_MEMBER_POSITION, COMPANY_MEMBER_AUTHORITY, COMPANY_MEMBER_DEPARTMENT)
VALUES (66, 29, '대리', '뷰어', '재무부');


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '윤지우', '010-9402-4056', 'twnbgn@example.com', 'C:\upload\image2.png', '일반', 0, '활성', '1997-03-27', TO_TIMESTAMP('2024-12-30 13:20:34', 'YYYY-MM-DD HH24:MI:SS'));


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '강예준', '010-6690-6582', 'goiswl@example.com', 'C:\upload\image5.png', '일반', 0, '활성', '2000-04-22', TO_TIMESTAMP('2024-12-24 06:26:50', 'YYYY-MM-DD HH24:MI:SS'));


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '김하은', '010-8798-6358', 'rpbqeh@example.com', 'C:\upload\image5.png', '일반', 0, '활성', '1998-04-06', TO_TIMESTAMP('2025-01-24 17:49:11', 'YYYY-MM-DD HH24:MI:SS'));


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '신은주', '010-9135-1538', 'zipedz@example.com', 'C:\upload\image1.png', '기업', 0, '활성', '1994-08-04', TO_TIMESTAMP('2024-10-03 15:35:27', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO TBL_COMPANY_MEMBER
(ID, COMPANY_ID, COMPANY_MEMBER_POSITION, COMPANY_MEMBER_AUTHORITY, COMPANY_MEMBER_DEPARTMENT)
VALUES (70, 14, '인턴', '뷰어', '전산부');


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '안민재', '010-2835-8470', 'lgiisd@example.com', 'C:\upload\image1.png', '기업', 0, '활성', '1994-12-10', TO_TIMESTAMP('2024-11-19 19:40:16', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO TBL_COMPANY_MEMBER
(ID, COMPANY_ID, COMPANY_MEMBER_POSITION, COMPANY_MEMBER_AUTHORITY, COMPANY_MEMBER_DEPARTMENT)
VALUES (71, 62, '팀장', '관리자', '영업부');


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '안준서', '010-5098-2621', 'zkdjtf@example.com', 'C:\upload\image3.png', '기업', 0, '활성', '1994-05-06', TO_TIMESTAMP('2024-12-07 11:29:09', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO TBL_COMPANY_MEMBER
(ID, COMPANY_ID, COMPANY_MEMBER_POSITION, COMPANY_MEMBER_AUTHORITY, COMPANY_MEMBER_DEPARTMENT)
VALUES (72, 51, '인턴', '뷰어', '영업부');


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '강민서', '010-7516-3901', 'gwalfw@example.com', 'C:\upload\image4.png', '일반', 0, '활성', '1989-01-01', TO_TIMESTAMP('2024-11-18 09:24:19', 'YYYY-MM-DD HH24:MI:SS'));


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '임지민', '010-3982-2874', 'ensvss@example.com', 'C:\upload\image4.png', '일반', 0, '활성', '1995-06-07', TO_TIMESTAMP('2025-03-21 01:30:18', 'YYYY-MM-DD HH24:MI:SS'));


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '정수빈', '010-4380-3350', 'vcnfkm@example.com', 'C:\upload\image1.png', '기업', 0, '활성', '1991-06-27', TO_TIMESTAMP('2025-02-10 02:49:20', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO TBL_COMPANY_MEMBER
(ID, COMPANY_ID, COMPANY_MEMBER_POSITION, COMPANY_MEMBER_AUTHORITY, COMPANY_MEMBER_DEPARTMENT)
VALUES (75, 19, '인턴', '뷰어', '영업부');


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '안건우', '010-7845-8290', 'pqamkt@example.com', 'C:\upload\image1.png', '기업', 0, '활성', '1999-02-19', TO_TIMESTAMP('2024-10-12 09:01:18', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO TBL_COMPANY_MEMBER
(ID, COMPANY_ID, COMPANY_MEMBER_POSITION, COMPANY_MEMBER_AUTHORITY, COMPANY_MEMBER_DEPARTMENT)
VALUES (76, 99, '사원', '뷰어', '전산부');


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '임현우', '010-7663-8980', 'rmiopa@example.com', 'C:\upload\image4.png', '일반', 0, '활성', '1985-05-25', TO_TIMESTAMP('2024-11-24 18:42:01', 'YYYY-MM-DD HH24:MI:SS'));


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '한민서', '010-9299-9360', 'xcstac@example.com', 'C:\upload\image4.png', '일반', 0, '활성', '1990-07-13', TO_TIMESTAMP('2025-02-11 04:51:06', 'YYYY-MM-DD HH24:MI:SS'));


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '강민준', '010-8388-1942', 'maoqlp@example.com', 'C:\upload\image4.png', '일반', 0, '활성', '1998-09-23', TO_TIMESTAMP('2024-10-03 15:05:19', 'YYYY-MM-DD HH24:MI:SS'));


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '임서연', '010-2233-8537', 'bazium@example.com', 'C:\upload\image4.png', '기업', 0, '활성', '1986-06-10', TO_TIMESTAMP('2025-01-10 06:18:48', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO TBL_COMPANY_MEMBER
(ID, COMPANY_ID, COMPANY_MEMBER_POSITION, COMPANY_MEMBER_AUTHORITY, COMPANY_MEMBER_DEPARTMENT)
VALUES (80, 20, '대리', '뷰어', '영업부');


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '서서현', '010-7303-6339', 'virvhz@example.com', 'C:\upload\image1.png', '일반', 0, '활성', '1998-04-02', TO_TIMESTAMP('2025-01-06 16:46:42', 'YYYY-MM-DD HH24:MI:SS'));


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '이지훈', '010-2954-5443', 'rtuwut@example.com', 'C:\upload\image5.png', '일반', 0, '활성', '1990-12-25', TO_TIMESTAMP('2024-11-20 20:21:00', 'YYYY-MM-DD HH24:MI:SS'));


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '김민서', '010-6256-1303', 'tkmknm@example.com', 'C:\upload\image5.png', '일반', 0, '활성', '2001-06-05', TO_TIMESTAMP('2024-11-30 19:04:50', 'YYYY-MM-DD HH24:MI:SS'));


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '윤민서', '010-3433-5580', 'ezmxcl@example.com', 'C:\upload\image1.png', '일반', 0, '활성', '1995-03-01', TO_TIMESTAMP('2025-02-16 15:25:22', 'YYYY-MM-DD HH24:MI:SS'));


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '류서윤', '010-5439-1706', 'yoruqr@example.com', 'C:\upload\image1.png', '기업', 0, '활성', '1988-12-02', TO_TIMESTAMP('2025-03-02 11:29:38', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO TBL_COMPANY_MEMBER
(ID, COMPANY_ID, COMPANY_MEMBER_POSITION, COMPANY_MEMBER_AUTHORITY, COMPANY_MEMBER_DEPARTMENT)
VALUES (85, 25, '팀장', '뷰어', '인사부');


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '장하은', '010-7357-7653', 'zlaquk@example.com', 'C:\upload\image3.png', '일반', 0, '활성', '1997-02-28', TO_TIMESTAMP('2025-02-07 18:26:04', 'YYYY-MM-DD HH24:MI:SS'));


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '한지훈', '010-8956-6153', 'xstcux@example.com', 'C:\upload\image4.png', '일반', 0, '활성', '1997-10-05', TO_TIMESTAMP('2025-02-10 19:11:38', 'YYYY-MM-DD HH24:MI:SS'));


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '박민재', '010-1327-2777', 'nkuzsd@example.com', 'C:\upload\image2.png', '기업', 0, '활성', '2001-09-07', TO_TIMESTAMP('2025-01-16 11:00:04', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO TBL_COMPANY_MEMBER
(ID, COMPANY_ID, COMPANY_MEMBER_POSITION, COMPANY_MEMBER_AUTHORITY, COMPANY_MEMBER_DEPARTMENT)
VALUES (88, 76, '인턴', '관리자', '마케팅부');


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '황지후', '010-7001-2007', 'eahuya@example.com', 'C:\upload\image4.png', '기업', 0, '활성', '1998-05-11', TO_TIMESTAMP('2025-01-24 14:37:06', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO TBL_COMPANY_MEMBER
(ID, COMPANY_ID, COMPANY_MEMBER_POSITION, COMPANY_MEMBER_AUTHORITY, COMPANY_MEMBER_DEPARTMENT)
VALUES (89, 47, '대리', '뷰어', '인사부');


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '송건우', '010-6604-6811', 'fmxxyz@example.com', 'C:\upload\image3.png', '일반', 0, '활성', '1985-06-06', TO_TIMESTAMP('2024-11-19 08:02:47', 'YYYY-MM-DD HH24:MI:SS'));


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '황예은', '010-5232-9427', 'fpabyj@example.com', 'C:\upload\image2.png', '기업', 0, '활성', '1985-07-05', TO_TIMESTAMP('2024-11-17 22:07:11', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO TBL_COMPANY_MEMBER
(ID, COMPANY_ID, COMPANY_MEMBER_POSITION, COMPANY_MEMBER_AUTHORITY, COMPANY_MEMBER_DEPARTMENT)
VALUES (91, 5, '대리', '관리자', '마케팅부');


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '권예준', '010-3472-8518', 'wzvxmx@example.com', 'C:\upload\image4.png', '일반', 0, '활성', '2001-09-26', TO_TIMESTAMP('2024-10-09 23:24:28', 'YYYY-MM-DD HH24:MI:SS'));


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '이하은', '010-4753-1842', 'nszslz@example.com', 'C:\upload\image1.png', '기업', 0, '활성', '1996-03-17', TO_TIMESTAMP('2025-01-17 12:14:59', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO TBL_COMPANY_MEMBER
(ID, COMPANY_ID, COMPANY_MEMBER_POSITION, COMPANY_MEMBER_AUTHORITY, COMPANY_MEMBER_DEPARTMENT)
VALUES (93, 60, '인턴', '뷰어', '영업부');


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '권윤서', '010-1164-7915', 'nakmti@example.com', 'C:\upload\image4.png', '일반', 0, '활성', '1999-04-16', TO_TIMESTAMP('2025-02-21 18:40:47', 'YYYY-MM-DD HH24:MI:SS'));


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '임지우', '010-5300-2036', 'tlcnxi@example.com', 'C:\upload\image4.png', '일반', 0, '활성', '2001-03-22', TO_TIMESTAMP('2024-12-19 07:59:30', 'YYYY-MM-DD HH24:MI:SS'));


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '류서현', '010-6642-4930', 'klmktw@example.com', 'C:\upload\image3.png', '기업', 0, '활성', '2000-08-28', TO_TIMESTAMP('2024-10-15 16:03:03', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO TBL_COMPANY_MEMBER
(ID, COMPANY_ID, COMPANY_MEMBER_POSITION, COMPANY_MEMBER_AUTHORITY, COMPANY_MEMBER_DEPARTMENT)
VALUES (96, 41, '사원', '뷰어', '재무부');


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '황서윤', '010-1829-4834', 'wpaptc@example.com', 'C:\upload\image2.png', '기업', 0, '활성', '1990-06-23', TO_TIMESTAMP('2024-09-28 07:23:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO TBL_COMPANY_MEMBER
(ID, COMPANY_ID, COMPANY_MEMBER_POSITION, COMPANY_MEMBER_AUTHORITY, COMPANY_MEMBER_DEPARTMENT)
VALUES (97, 64, '대리', '관리자', '인사부');


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '송서윤', '010-5420-4307', 'tuouze@example.com', 'C:\upload\image4.png', '일반', 0, '활성', '2001-03-01', TO_TIMESTAMP('2025-02-04 06:14:06', 'YYYY-MM-DD HH24:MI:SS'));


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '류윤서', '010-3135-1212', 'uhgpsv@example.com', 'C:\upload\image5.png', '기업', 0, '활성', '1990-08-23', TO_TIMESTAMP('2024-11-11 09:45:17', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO TBL_COMPANY_MEMBER
(ID, COMPANY_ID, COMPANY_MEMBER_POSITION, COMPANY_MEMBER_AUTHORITY, COMPANY_MEMBER_DEPARTMENT)
VALUES (99, 91, '대리', '뷰어', '전산부');


INSERT INTO TBL_MEMBER
(ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_PROFILE_PATH, MEMBER_CLASS, MEMBER_POINT, MEMBER_STATUS, MEMBER_BIRTH, MEMBER_RECENT_LOGIN)
VALUES (SEQ_MEMBER.NEXTVAL, '류민준', '010-3213-1362', 'hvhwqp@example.com', 'C:\upload\image5.png', '기업', 0, '활성', '1985-06-08', TO_TIMESTAMP('2024-10-16 17:13:16', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO TBL_COMPANY_MEMBER
(ID, COMPANY_ID, COMPANY_MEMBER_POSITION, COMPANY_MEMBER_AUTHORITY, COMPANY_MEMBER_DEPARTMENT)
VALUES (100, 89, '팀장', '관리자', '영업부');