INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '디지털 마케팅 전략 실습', '현업 전문가와 함께하는 실질적인 직무 체험 워크숍입니다.', '진행중', '심사중', TO_DATE('2025-11-28', 'YYYY-MM-DD'), 66885, 0, 'C:\upload\thumbnail5.png', 18, 20124);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '블록체인 개발자 심화 체험', '실제 현장에서 사용되는 도구와 기술을 체험합니다.', '진행중', '심사중', TO_DATE('2026-03-11', 'YYYY-MM-DD'), 75258, 1, 'C:\upload\thumbnail2.png', 46, 40101);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, 'UI/UX 디자이너 프로젝트 참여', '직접적인 실무 환경을 경험하며 성장을 지원합니다.', '진행중', '심사중', TO_DATE('2026-01-28', 'YYYY-MM-DD'), 65210, 0, 'C:\upload\thumbnail3.png', 87, 20701);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '게임 프로그래밍 기초부터 실무까지', '업계에서 요구하는 핵심 기술을 실습하며 익힙니다.', '진행중', '심사중', TO_DATE('2025-04-24', 'YYYY-MM-DD'), 30916, 1, 'C:\upload\thumbnail4.png', 27, 12203);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '블록체인 개발자 심화 체험', '개별 맞춤형 멘토링을 통해 실력을 강화할 수 있습니다.', '진행중', '심사중', TO_DATE('2025-09-28', 'YYYY-MM-DD'), 52114, 1, 'C:\upload\thumbnail4.png', 74, 31310);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '프로덕트 매니저 실무 워크숍', '다양한 산업 사례를 바탕으로 실질적인 학습을 제공합니다.', '진행중', '심사중', TO_DATE('2025-12-13', 'YYYY-MM-DD'), 59055, 0, 'C:\upload\thumbnail4.png', 78, 30507);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '소프트웨어 테스트 엔지니어 체험', '개별 맞춤형 멘토링을 통해 실력을 강화할 수 있습니다.', '진행중', '심사중', TO_DATE('2026-01-05', 'YYYY-MM-DD'), 71140, 1, 'C:\upload\thumbnail3.png', 34, 10936);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '디지털 마케팅 전략 실습', '최신 기술 트렌드를 학습하며 실습 기회를 제공합니다.', '진행중', '심사중', TO_DATE('2026-02-20', 'YYYY-MM-DD'), 56383, 0, 'C:\upload\thumbnail5.png', 69, 30705);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '클라우드 엔지니어 인턴십 체험', '실제 현장에서 사용되는 도구와 기술을 체험합니다.', '진행중', '심사중', TO_DATE('2025-09-22', 'YYYY-MM-DD'), 46108, 0, 'C:\upload\thumbnail5.png', 89, 30118);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '데이터 시각화 전문가 되기', '직무별 특화된 학습 모듈을 통해 전문성을 높입니다.', '진행중', '심사중', TO_DATE('2025-11-16', 'YYYY-MM-DD'), 20556, 1, 'C:\upload\thumbnail1.png', 46, 50415);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '클라우드 엔지니어 인턴십 체험', '개별 맞춤형 멘토링을 통해 실력을 강화할 수 있습니다.', '진행중', '심사중', TO_DATE('2025-08-18', 'YYYY-MM-DD'), 63447, 0, 'C:\upload\thumbnail4.png', 22, 21101);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '프로덕트 매니저 실무 워크숍', '현업과 연계된 워크숍으로 실질적인 체험 기회를 제공합니다.', '진행중', '심사중', TO_DATE('2025-12-14', 'YYYY-MM-DD'), 35907, 0, 'C:\upload\thumbnail5.png', 52, 30811);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '모바일 앱 개발 실전 프로젝트', '직무별 특화된 학습 모듈을 통해 전문성을 높입니다.', '진행중', '심사중', TO_DATE('2025-10-05', 'YYYY-MM-DD'), 54666, 1, 'C:\upload\thumbnail5.png', 87, 40115);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '마케팅 전문가 실전 워크숍', '전문 강사진의 지도 아래 심화된 교육을 제공합니다.', '진행중', '심사중', TO_DATE('2025-08-19', 'YYYY-MM-DD'), 58410, 1, 'C:\upload\thumbnail4.png', 30, 50506);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '데이터 분석가 직무 체험', '팀 프로젝트를 통해 협업 능력을 향상시킵니다.', '진행중', '심사중', TO_DATE('2025-07-06', 'YYYY-MM-DD'), 78983, 1, 'C:\upload\thumbnail2.png', 15, 50607);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '블록체인 개발자 심화 체험', '직접적인 실무 환경을 경험하며 성장을 지원합니다.', '진행중', '심사중', TO_DATE('2025-08-18', 'YYYY-MM-DD'), 59073, 0, 'C:\upload\thumbnail1.png', 58, 30404);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '블록체인 개발자 심화 체험', '현업 전문가와 함께하는 실질적인 직무 체험 워크숍입니다.', '진행중', '심사중', TO_DATE('2025-10-19', 'YYYY-MM-DD'), 43836, 0, 'C:\upload\thumbnail5.png', 89, 20124);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '증강현실(AR) 개발 실습', '다양한 실습 과제를 통해 이론과 실무를 연결합니다.', '진행중', '심사중', TO_DATE('2025-03-29', 'YYYY-MM-DD'), 19899, 0, 'C:\upload\thumbnail1.png', 38, 20108);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '게임 프로그래밍 기초부터 실무까지', '직무와 연관된 문제 해결 능력을 집중적으로 훈련합니다.', '진행중', '심사중', TO_DATE('2025-11-27', 'YYYY-MM-DD'), 33400, 1, 'C:\upload\thumbnail3.png', 50, 50606);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '데이터 분석가 직무 체험', '실무 프로젝트 중심의 직무 훈련 프로그램입니다.', '진행중', '심사중', TO_DATE('2026-02-25', 'YYYY-MM-DD'), 12126, 0, 'C:\upload\thumbnail3.png', 38, 31307);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '프로덕트 매니저 실무 워크숍', '실제 현장에서 사용되는 도구와 기술을 체험합니다.', '진행중', '심사중', TO_DATE('2025-08-15', 'YYYY-MM-DD'), 85066, 0, 'C:\upload\thumbnail3.png', 85, 30520);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '데이터 분석가 직무 체험', '전문 강사진의 지도 아래 심화된 교육을 제공합니다.', '진행중', '심사중', TO_DATE('2025-04-21', 'YYYY-MM-DD'), 61428, 1, 'C:\upload\thumbnail2.png', 19, 30608);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '모바일 앱 개발 실전 프로젝트', '참여형 학습 모델로 심화된 직무 능력을 배양합니다.', '진행중', '심사중', TO_DATE('2025-04-24', 'YYYY-MM-DD'), 12836, 1, 'C:\upload\thumbnail1.png', 5, 21202);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '백엔드 개발자 실무 체험 프로그램', '현업 전문가와 함께하는 실질적인 직무 체험 워크숍입니다.', '진행중', '심사중', TO_DATE('2025-11-17', 'YYYY-MM-DD'), 28832, 1, 'C:\upload\thumbnail3.png', 92, 50501);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '소프트웨어 테스트 엔지니어 체험', '실무 프로젝트 중심의 직무 훈련 프로그램입니다.', '진행중', '심사중', TO_DATE('2026-02-02', 'YYYY-MM-DD'), 97916, 0, 'C:\upload\thumbnail5.png', 1, 31405);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '프로덕트 매니저 실무 워크숍', '실무 프로젝트 중심의 직무 훈련 프로그램입니다.', '진행중', '심사중', TO_DATE('2026-03-21', 'YYYY-MM-DD'), 52555, 0, 'C:\upload\thumbnail4.png', 63, 40121);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '소프트웨어 테스트 엔지니어 체험', '다양한 실습 과제를 통해 이론과 실무를 연결합니다.', '진행중', '심사중', TO_DATE('2025-09-22', 'YYYY-MM-DD'), 93850, 0, 'C:\upload\thumbnail1.png', 46, 40122);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '디지털 마케팅 전략 실습', '개별 맞춤형 멘토링을 통해 실력을 강화할 수 있습니다.', '진행중', '심사중', TO_DATE('2025-10-01', 'YYYY-MM-DD'), 69840, 1, 'C:\upload\thumbnail3.png', 12, 11501);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, 'QA 엔지니어링 실무 워크숍', '다양한 산업 사례를 바탕으로 실질적인 학습을 제공합니다.', '진행중', '심사중', TO_DATE('2025-05-25', 'YYYY-MM-DD'), 98307, 1, 'C:\upload\thumbnail4.png', 32, 30626);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, 'AI 엔지니어링 첫걸음', '다양한 산업 사례를 바탕으로 실질적인 학습을 제공합니다.', '진행중', '심사중', TO_DATE('2025-04-08', 'YYYY-MM-DD'), 73252, 0, 'C:\upload\thumbnail5.png', 36, 12005);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '프로덕트 매니저 실무 워크숍', '업계에서 요구하는 핵심 기술을 실습하며 익힙니다.', '진행중', '심사중', TO_DATE('2026-02-13', 'YYYY-MM-DD'), 78948, 1, 'C:\upload\thumbnail5.png', 12, 20211);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, 'QA 엔지니어링 실무 워크숍', '기술뿐만 아니라 비즈니스 관점의 전략적 사고를 기릅니다.', '진행중', '심사중', TO_DATE('2025-07-16', 'YYYY-MM-DD'), 71477, 1, 'C:\upload\thumbnail3.png', 98, 12102);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '소프트웨어 테스트 엔지니어 체험', '참여형 학습 모델로 심화된 직무 능력을 배양합니다.', '진행중', '심사중', TO_DATE('2026-02-17', 'YYYY-MM-DD'), 14118, 1, 'C:\upload\thumbnail2.png', 6, 12207);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '영상 제작 전문가 미리 체험하기', '실제 현장에서 사용되는 도구와 기술을 체험합니다.', '진행중', '심사중', TO_DATE('2025-11-01', 'YYYY-MM-DD'), 56832, 0, 'C:\upload\thumbnail3.png', 45, 11903);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '프로덕트 매니저 실무 워크숍', '다양한 산업 사례를 바탕으로 실질적인 학습을 제공합니다.', '진행중', '심사중', TO_DATE('2025-10-17', 'YYYY-MM-DD'), 47385, 1, 'C:\upload\thumbnail3.png', 55, 30519);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, 'QA 엔지니어링 실무 워크숍', '개별 맞춤형 멘토링을 통해 실력을 강화할 수 있습니다.', '진행중', '심사중', TO_DATE('2026-03-23', 'YYYY-MM-DD'), 93479, 0, 'C:\upload\thumbnail2.png', 51, 10806);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '모바일 앱 개발 실전 프로젝트', '현업 전문가와 함께하는 실질적인 직무 체험 워크숍입니다.', '진행중', '심사중', TO_DATE('2025-05-14', 'YYYY-MM-DD'), 64841, 1, 'C:\upload\thumbnail5.png', 67, 21103);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, 'UI/UX 디자이너 프로젝트 참여', '개별 맞춤형 멘토링을 통해 실력을 강화할 수 있습니다.', '진행중', '심사중', TO_DATE('2025-06-05', 'YYYY-MM-DD'), 44618, 1, 'C:\upload\thumbnail3.png', 50, 30614);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '보안 엔지니어 직무 가이드', '업계에서 요구하는 핵심 기술을 실습하며 익힙니다.', '진행중', '심사중', TO_DATE('2025-05-07', 'YYYY-MM-DD'), 74541, 0, 'C:\upload\thumbnail1.png', 7, 21601);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '프로덕트 매니저 실무 워크숍', '팀 프로젝트를 통해 협업 능력을 향상시킵니다.', '진행중', '심사중', TO_DATE('2025-11-21', 'YYYY-MM-DD'), 44877, 1, 'C:\upload\thumbnail5.png', 17, 30814);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '게임 디자이너의 하루 체험', '현업 전문가와 함께하는 실질적인 직무 체험 워크숍입니다.', '진행중', '심사중', TO_DATE('2025-05-08', 'YYYY-MM-DD'), 50906, 1, 'C:\upload\thumbnail1.png', 63, 50107);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, 'QA 엔지니어링 실무 워크숍', '기술뿐만 아니라 비즈니스 관점의 전략적 사고를 기릅니다.', '진행중', '심사중', TO_DATE('2025-12-20', 'YYYY-MM-DD'), 35645, 1, 'C:\upload\thumbnail4.png', 83, 30806);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '백엔드 개발자 실무 체험 프로그램', '학습한 내용을 즉시 적용할 수 있는 훈련 기회를 제공합니다.', '진행중', '심사중', TO_DATE('2025-10-24', 'YYYY-MM-DD'), 15709, 1, 'C:\upload\thumbnail2.png', 89, 21103);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, 'UI/UX 디자이너 프로젝트 참여', '현업과 연계된 워크숍으로 실질적인 체험 기회를 제공합니다.', '진행중', '심사중', TO_DATE('2026-02-27', 'YYYY-MM-DD'), 69030, 1, 'C:\upload\thumbnail3.png', 94, 11115);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '게임 디자이너의 하루 체험', '직무와 연관된 문제 해결 능력을 집중적으로 훈련합니다.', '진행중', '심사중', TO_DATE('2025-10-16', 'YYYY-MM-DD'), 15802, 1, 'C:\upload\thumbnail4.png', 19, 30603);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '마케팅 전문가 실전 워크숍', '직접적인 실무 환경을 경험하며 성장을 지원합니다.', '진행중', '심사중', TO_DATE('2025-12-15', 'YYYY-MM-DD'), 90009, 0, 'C:\upload\thumbnail1.png', 36, 50410);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, 'AI 엔지니어링 첫걸음', '실질적인 피드백을 통해 지속적인 성장 기회를 제공합니다.', '진행중', '심사중', TO_DATE('2026-03-16', 'YYYY-MM-DD'), 76557, 0, 'C:\upload\thumbnail2.png', 55, 30509);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '데이터 분석가 직무 체험', '직무와 연관된 문제 해결 능력을 집중적으로 훈련합니다.', '진행중', '심사중', TO_DATE('2025-05-01', 'YYYY-MM-DD'), 58084, 1, 'C:\upload\thumbnail4.png', 5, 12202);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, 'UI/UX 디자이너 프로젝트 참여', '다양한 산업 사례를 바탕으로 실질적인 학습을 제공합니다.', '진행중', '심사중', TO_DATE('2026-01-01', 'YYYY-MM-DD'), 58296, 1, 'C:\upload\thumbnail1.png', 77, 30103);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '프로덕트 매니저 실무 워크숍', '현업과 연계된 워크숍으로 실질적인 체험 기회를 제공합니다.', '진행중', '심사중', TO_DATE('2025-11-29', 'YYYY-MM-DD'), 55552, 1, 'C:\upload\thumbnail4.png', 98, 50202);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, 'IoT 개발자 실습 프로그램', '현업 전문가와 함께하는 실질적인 직무 체험 워크숍입니다.', '진행중', '심사중', TO_DATE('2025-05-19', 'YYYY-MM-DD'), 40756, 0, 'C:\upload\thumbnail2.png', 51, 10920);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, 'QA 엔지니어링 실무 워크숍', '기술뿐만 아니라 비즈니스 관점의 전략적 사고를 기릅니다.', '진행중', '심사중', TO_DATE('2026-03-25', 'YYYY-MM-DD'), 65101, 1, 'C:\upload\thumbnail3.png', 94, 30406);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, 'QA 엔지니어링 실무 워크숍', '개별 맞춤형 멘토링을 통해 실력을 강화할 수 있습니다.', '진행중', '심사중', TO_DATE('2026-02-13', 'YYYY-MM-DD'), 76790, 1, 'C:\upload\thumbnail5.png', 87, 31408);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '게임 프로그래밍 기초부터 실무까지', '직무별 특화된 학습 모듈을 통해 전문성을 높입니다.', '진행중', '심사중', TO_DATE('2026-01-01', 'YYYY-MM-DD'), 89476, 1, 'C:\upload\thumbnail1.png', 99, 30111);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '프론트엔드 개발 마스터 도전', '다양한 산업 사례를 바탕으로 실질적인 학습을 제공합니다.', '진행중', '심사중', TO_DATE('2025-04-18', 'YYYY-MM-DD'), 93647, 0, 'C:\upload\thumbnail1.png', 24, 30613);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '디지털 마케팅 전략 실습', '전문 강사진의 지도 아래 심화된 교육을 제공합니다.', '진행중', '심사중', TO_DATE('2026-03-05', 'YYYY-MM-DD'), 25607, 1, 'C:\upload\thumbnail1.png', 5, 12001);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, 'AI 엔지니어링 첫걸음', '자격증 취득을 목표로 설계된 직무 전문 과정입니다.', '진행중', '심사중', TO_DATE('2026-03-19', 'YYYY-MM-DD'), 13796, 1, 'C:\upload\thumbnail5.png', 48, 50408);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '보안 엔지니어 직무 가이드', '개별 맞춤형 멘토링을 통해 실력을 강화할 수 있습니다.', '진행중', '심사중', TO_DATE('2025-06-19', 'YYYY-MM-DD'), 52430, 1, 'C:\upload\thumbnail3.png', 37, 50414);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '모바일 앱 개발 실전 프로젝트', '실제 현장에서 사용되는 도구와 기술을 체험합니다.', '진행중', '심사중', TO_DATE('2025-10-26', 'YYYY-MM-DD'), 90955, 1, 'C:\upload\thumbnail4.png', 58, 50303);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '소프트웨어 테스트 엔지니어 체험', '현업 전문가와 함께하는 실질적인 직무 체험 워크숍입니다.', '진행중', '심사중', TO_DATE('2026-01-07', 'YYYY-MM-DD'), 18720, 1, 'C:\upload\thumbnail3.png', 63, 50107);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '백엔드 개발자 실무 체험 프로그램', '학습한 내용을 즉시 적용할 수 있는 훈련 기회를 제공합니다.', '진행중', '심사중', TO_DATE('2025-07-04', 'YYYY-MM-DD'), 64038, 1, 'C:\upload\thumbnail5.png', 100, 21102);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '프로덕트 매니저 실무 워크숍', '직무와 연관된 문제 해결 능력을 집중적으로 훈련합니다.', '진행중', '심사중', TO_DATE('2026-01-10', 'YYYY-MM-DD'), 57535, 1, 'C:\upload\thumbnail3.png', 19, 50106);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '데이터 시각화 전문가 되기', '다양한 실습 과제를 통해 이론과 실무를 연결합니다.', '진행중', '심사중', TO_DATE('2026-01-11', 'YYYY-MM-DD'), 66081, 0, 'C:\upload\thumbnail3.png', 77, 30812);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '모바일 앱 개발 실전 프로젝트', '직무별 특화된 학습 모듈을 통해 전문성을 높입니다.', '진행중', '심사중', TO_DATE('2025-11-12', 'YYYY-MM-DD'), 75582, 0, 'C:\upload\thumbnail4.png', 90, 21108);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, 'AI 엔지니어링 첫걸음', '직무와 연관된 문제 해결 능력을 집중적으로 훈련합니다.', '진행중', '심사중', TO_DATE('2026-01-06', 'YYYY-MM-DD'), 93826, 0, 'C:\upload\thumbnail5.png', 15, 100502);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '모바일 앱 개발 실전 프로젝트', '팀 프로젝트를 통해 협업 능력을 향상시킵니다.', '진행중', '심사중', TO_DATE('2025-11-04', 'YYYY-MM-DD'), 42309, 0, 'C:\upload\thumbnail5.png', 61, 20405);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, 'IoT 개발자 실습 프로그램', '전문 강사진의 지도 아래 심화된 교육을 제공합니다.', '진행중', '심사중', TO_DATE('2025-09-26', 'YYYY-MM-DD'), 81175, 0, 'C:\upload\thumbnail1.png', 1, 20102);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '모바일 앱 개발 실전 프로젝트', '직무별 특화된 학습 모듈을 통해 전문성을 높입니다.', '진행중', '심사중', TO_DATE('2025-08-05', 'YYYY-MM-DD'), 77994, 0, 'C:\upload\thumbnail2.png', 36, 20124);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, 'QA 엔지니어링 실무 워크숍', '직접적인 실무 환경을 경험하며 성장을 지원합니다.', '진행중', '심사중', TO_DATE('2025-09-04', 'YYYY-MM-DD'), 86187, 0, 'C:\upload\thumbnail1.png', 9, 50211);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '영상 제작 전문가 미리 체험하기', '다양한 실습 과제를 통해 이론과 실무를 연결합니다.', '진행중', '심사중', TO_DATE('2025-12-23', 'YYYY-MM-DD'), 15307, 0, 'C:\upload\thumbnail4.png', 4, 11903);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '디지털 마케팅 전략 실습', '직접적인 실무 환경을 경험하며 성장을 지원합니다.', '진행중', '심사중', TO_DATE('2025-07-31', 'YYYY-MM-DD'), 57420, 0, 'C:\upload\thumbnail3.png', 30, 20415);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '데이터 분석가 직무 체험', '학습한 내용을 즉시 적용할 수 있는 훈련 기회를 제공합니다.', '진행중', '심사중', TO_DATE('2026-03-17', 'YYYY-MM-DD'), 44583, 1, 'C:\upload\thumbnail4.png', 44, 20419);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, 'AI 엔지니어링 첫걸음', '직무와 연관된 문제 해결 능력을 집중적으로 훈련합니다.', '진행중', '심사중', TO_DATE('2025-09-04', 'YYYY-MM-DD'), 82620, 0, 'C:\upload\thumbnail4.png', 83, 12209);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, 'UI/UX 디자이너 프로젝트 참여', '직무별 특화된 학습 모듈을 통해 전문성을 높입니다.', '진행중', '심사중', TO_DATE('2025-09-04', 'YYYY-MM-DD'), 75886, 1, 'C:\upload\thumbnail2.png', 70, 30801);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '증강현실(AR) 개발 실습', '팀 프로젝트를 통해 협업 능력을 향상시킵니다.', '진행중', '심사중', TO_DATE('2025-11-23', 'YYYY-MM-DD'), 29100, 1, 'C:\upload\thumbnail5.png', 33, 21001);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '데이터 분석가 직무 체험', '실제 현장에서 사용되는 도구와 기술을 체험합니다.', '진행중', '심사중', TO_DATE('2025-11-21', 'YYYY-MM-DD'), 27586, 0, 'C:\upload\thumbnail5.png', 54, 31411);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, 'UI/UX 디자이너 프로젝트 참여', '참여자 간의 네트워킹 기회를 제공하여 경험을 공유합니다.', '진행중', '심사중', TO_DATE('2025-06-23', 'YYYY-MM-DD'), 22478, 1, 'C:\upload\thumbnail5.png', 32, 50101);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '클라우드 엔지니어 인턴십 체험', '현업 전문가와 함께하는 실질적인 직무 체험 워크숍입니다.', '진행중', '심사중', TO_DATE('2026-01-25', 'YYYY-MM-DD'), 87823, 1, 'C:\upload\thumbnail1.png', 57, 21101);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '게임 프로그래밍 기초부터 실무까지', '직접적인 실무 환경을 경험하며 성장을 지원합니다.', '진행중', '심사중', TO_DATE('2025-07-31', 'YYYY-MM-DD'), 74749, 0, 'C:\upload\thumbnail5.png', 57, 12203);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '디지털 마케팅 전략 실습', '다양한 실습 과제를 통해 이론과 실무를 연결합니다.', '진행중', '심사중', TO_DATE('2025-09-09', 'YYYY-MM-DD'), 35896, 1, 'C:\upload\thumbnail3.png', 30, 10910);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, 'AI 엔지니어링 첫걸음', '최신 기술 트렌드를 학습하며 실습 기회를 제공합니다.', '진행중', '심사중', TO_DATE('2025-12-02', 'YYYY-MM-DD'), 43881, 0, 'C:\upload\thumbnail1.png', 39, 30633);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '데이터 분석가 직무 체험', '다양한 실습 과제를 통해 이론과 실무를 연결합니다.', '진행중', '심사중', TO_DATE('2025-12-07', 'YYYY-MM-DD'), 58190, 1, 'C:\upload\thumbnail1.png', 3, 20904);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, 'AI 엔지니어링 첫걸음', '실무 프로젝트 중심의 직무 훈련 프로그램입니다.', '진행중', '심사중', TO_DATE('2025-05-04', 'YYYY-MM-DD'), 15701, 1, 'C:\upload\thumbnail3.png', 54, 12203);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '영상 제작 전문가 미리 체험하기', '참여형 학습 모델로 심화된 직무 능력을 배양합니다.', '진행중', '심사중', TO_DATE('2026-02-02', 'YYYY-MM-DD'), 50210, 0, 'C:\upload\thumbnail4.png', 96, 40125);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '데이터 시각화 전문가 되기', '다양한 산업 사례를 바탕으로 실질적인 학습을 제공합니다.', '진행중', '심사중', TO_DATE('2025-10-11', 'YYYY-MM-DD'), 63769, 1, 'C:\upload\thumbnail2.png', 10, 12209);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '마케팅 전문가 실전 워크숍', '자격증 취득을 목표로 설계된 직무 전문 과정입니다.', '진행중', '심사중', TO_DATE('2025-06-16', 'YYYY-MM-DD'), 47326, 0, 'C:\upload\thumbnail1.png', 6, 21506);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '디지털 마케팅 전략 실습', '기술뿐만 아니라 비즈니스 관점의 전략적 사고를 기릅니다.', '진행중', '심사중', TO_DATE('2025-06-23', 'YYYY-MM-DD'), 49811, 1, 'C:\upload\thumbnail3.png', 64, 20508);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, 'IoT 개발자 실습 프로그램', '기술뿐만 아니라 비즈니스 관점의 전략적 사고를 기릅니다.', '진행중', '심사중', TO_DATE('2025-10-01', 'YYYY-MM-DD'), 63802, 1, 'C:\upload\thumbnail4.png', 57, 50608);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, 'IoT 개발자 실습 프로그램', '최신 기술 트렌드를 학습하며 실습 기회를 제공합니다.', '진행중', '심사중', TO_DATE('2025-09-07', 'YYYY-MM-DD'), 43928, 0, 'C:\upload\thumbnail5.png', 9, 30505);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '디지털 마케팅 전략 실습', '최신 기술 트렌드를 학습하며 실습 기회를 제공합니다.', '진행중', '심사중', TO_DATE('2026-03-15', 'YYYY-MM-DD'), 35112, 1, 'C:\upload\thumbnail2.png', 5, 30107);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, 'AI 엔지니어링 첫걸음', '현업과 연계된 워크숍으로 실질적인 체험 기회를 제공합니다.', '진행중', '심사중', TO_DATE('2025-09-13', 'YYYY-MM-DD'), 11507, 1, 'C:\upload\thumbnail1.png', 75, 20101);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '백엔드 개발자 실무 체험 프로그램', '직무별 특화된 학습 모듈을 통해 전문성을 높입니다.', '진행중', '심사중', TO_DATE('2025-09-28', 'YYYY-MM-DD'), 93912, 0, 'C:\upload\thumbnail2.png', 31, 21511);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '게임 디자이너의 하루 체험', '직접적인 실무 환경을 경험하며 성장을 지원합니다.', '진행중', '심사중', TO_DATE('2025-10-05', 'YYYY-MM-DD'), 39354, 0, 'C:\upload\thumbnail1.png', 86, 20804);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '클라우드 엔지니어 인턴십 체험', '직접적인 실무 환경을 경험하며 성장을 지원합니다.', '진행중', '심사중', TO_DATE('2025-07-07', 'YYYY-MM-DD'), 40265, 1, 'C:\upload\thumbnail1.png', 57, 21001);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '증강현실(AR) 개발 실습', '전문 강사진의 지도 아래 심화된 교육을 제공합니다.', '진행중', '심사중', TO_DATE('2025-10-22', 'YYYY-MM-DD'), 18926, 0, 'C:\upload\thumbnail3.png', 35, 30202);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '블록체인 개발자 심화 체험', '학습한 내용을 즉시 적용할 수 있는 훈련 기회를 제공합니다.', '진행중', '심사중', TO_DATE('2025-07-15', 'YYYY-MM-DD'), 41947, 1, 'C:\upload\thumbnail2.png', 64, 20123);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '클라우드 엔지니어 인턴십 체험', '현업과 연계된 워크숍으로 실질적인 체험 기회를 제공합니다.', '진행중', '심사중', TO_DATE('2025-06-16', 'YYYY-MM-DD'), 85892, 0, 'C:\upload\thumbnail3.png', 38, 40116);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '블록체인 개발자 심화 체험', '기술뿐만 아니라 비즈니스 관점의 전략적 사고를 기릅니다.', '진행중', '심사중', TO_DATE('2025-07-25', 'YYYY-MM-DD'), 12752, 0, 'C:\upload\thumbnail3.png', 96, 20509);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, 'AI 엔지니어링 첫걸음', '업계에서 요구하는 핵심 기술을 실습하며 익힙니다.', '진행중', '심사중', TO_DATE('2025-11-24', 'YYYY-MM-DD'), 16756, 1, 'C:\upload\thumbnail3.png', 37, 20418);

INSERT INTO TBL_PROGRAM
(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID)
VALUES (SEQ_PROGRAM.NEXTVAL, '증강현실(AR) 개발 실습', '다양한 실습 과제를 통해 이론과 실무를 연결합니다.', '진행중', '심사중', TO_DATE('2025-05-02', 'YYYY-MM-DD'), 32178, 0, 'C:\upload\thumbnail2.png', 43, 30632);