/*도서 테이블(수정 필요해보임)*/
CREATE TABLE TBL_BOOK(
	ID NUMBER CONSTRAINT PK_BOOK PRIMARY KEY,
	BOOK_TITLE VARCHAR2(1000) NOT NULL,
	BOOK_AUTHOR VARCHAR2(1000) NOT NULL,
	BOOK_TRANSLATOR VARCHAR2(1000),
	BOOK_PUBLISHER VARCHAR2(1000),
	BOOK_PUBLISHED_DATE DATE,
	CREATED_DATE DATE DEFAULT SYSDATE,
	UPDATED_DATE DATE DEFAULT SYSDATE
);

/*개인회원 테이블*/
CREATE TABLE TBL_MEMBER(
	ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
	MEMBER_EMAIL VARCHAR2(1000) NOT NULL,
	MEMBER_PASSWORD VARCHAR2(1000),
	MEMBER_NAME VARCHAR2(1000),
	MEMBER_POINT NUMBER DEFAULT 0,
	CREATED_DATE DATE DEFAULT SYSDATE,
	UPDATED_DATE DATE DEFAULT SYSDATE
); 

/*단체회원 테이블*/
CREATE TABLE TBL_VOLUNTEER(
	ID NUMBER CONSTRAINT PK_VOLUNTEER PRIMARY KEY,
	VOLUNTEER_NAME VARCHAR2(1000) NOT NULL,
	VOLUNTEER_EMAIL VARCHAR2(1000) NOT NULL,
	VOLUNTEER_PASSWORD VARCHAR2(1000) NOT NULL,
	VOLUNTEER_MAIN_ADDRESS VARCHAR2(1000),
	VOLUNTEER_SUB_ADDRESS VARCHAR2(1000),
	VOLUNTEER_TEL VARCHAR2(1000),
	CREATED_DATE DATE DEFAULT SYSDATE,
	UPDATED_DATE DATE DEFAULT SYSDATE
);

/*관리자 테이블*/
CREATE TABLE TBL_ADMIN(
	ID NUMBER CONSTRAINT PK_ADMIN PRIMARY KEY,
	ADMIN_ID VARCHAR2(1000) NOT NULL,
	ADMIN_PASSWORD VARCHAR2(1000) NOT NULL,
	CREATED_DATE DATE DEFAULT SYSDATE,
	UPDATED_DATE DATE DEFAULT SYSDATE
);

/*독후감 테이블*/
CREATE TABLE TBL_BOOK_REPORT(
	ID NUMBER CONSTRAINT PK_BOOK_REPORT PRIMARY KEY,
	BOOK_REPORT_TITLE VARCHAR2(1000) NOT NULL,
	BOOK_REPORT_DETAIL VARCHAR2(1000) NOT NULL,
	BOOK_REPORT_VIEW_COUNT NUMBER DEFAULT 0,
	MEMBER_ID NUMBER NOT NULL,
	BOOK_ID NUMBER NOT NULL,
	CREATED_DATE DATE DEFAULT SYSDATE,
	UPDATED_DATE DATE DEFAULT SYSDATE,
	CONSTRAINT FK_BOOK_REPORT_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID) ON DELETE CASCADE,
	CONSTRAINT FK_BOOK_REPORT_BOOK FOREIGN KEY(BOOK_ID)
	REFERENCES TBL_BOOK(ID) ON DELETE CASCADE
);

/*독후감 좋아요 테이블*/
CREATE TABLE TBL_LIKE(
	ID NUMBER CONSTRAINT PK_LIKE PRIMARY KEY,
	BOOK_REPORT_ID NUMBER NOT NULL,
	MEMBER_ID NUMBER NOT NULL,
	CREATED_DATE DATE DEFAULT SYSDATE,
	UPDATED_DATE DATE DEFAULT SYSDATE,
	CONSTRAINT FK_LIKE_BOOK_REPORT FOREIGN KEY(BOOK_REPORT_ID)
	REFERENCES TBL_BOOK_REPORT(ID) ON DELETE CASCADE,
	CONSTRAINT FK_LIKE_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID) ON DELETE CASCADE
);

/*책 스크랩 테이블*/
CREATE TABLE TBL_SCRAP(
	ID NUMBER CONSTRAINT PK_SCRAP PRIMARY KEY,
	BOOK_ID NUMBER NOT NULL,
	MEMBER_ID NUMBER NOT NULL,
	CREATED_DATE DATE DEFAULT SYSDATE,
	UPDATED_DATE DATE DEFAULT SYSDATE,
	CONSTRAINT FK_SCRAP_BOOK FOREIGN KEY(BOOK_ID)
	REFERENCES TBL_BOOK(ID) ON DELETE CASCADE,
	CONSTRAINT FK_SCRAP_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID) ON DELETE CASCADE
);

/*신고 테이블(슈퍼키)*/ /*DETAIL도 NOT NULL로 할지 고민중*/
CREATE TABLE TBL_REPORT(
	ID NUMBER CONSTRAINT PK_REPORT PRIMARY KEY,
	MEMBER_ID NUMBER NOT NULL,
	REPORT_TITLE VARCHAR2(1000) NOT NULL,
	REPORT_DETAIL VARCHAR2(1000),
	REPORT_TYPE VARCHAR2(1000) NOT NULL,
	REPORT_STATUS VARCHAR2(1000) DEFAULT '처리중',
	CREATED_DATE DATE DEFAULT SYSDATE,
	UPDATED_DATE DATE DEFAULT SYSDATE,
	CONSTRAINT FK_REPORT_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID) ON DELETE CASCADE
);

/*독후감 신고 테이블(서브키)*/
CREATE TABLE TBL_BOOK_REPORT_REPORT(
	ID NUMBER CONSTRAINT PK_BOOK_REPORT_REPORT PRIMARY KEY,
	BOOK_REPORT_ID NUMBER NOT NULL,
	CONSTRAINT FK_BOOK_REPORT_REPORT_REPORT FOREIGN KEY(ID)
	REFERENCES TBL_REPORT(ID) ON DELETE CASCADE,
	CONSTRAINT FK_BOOK_REPORT_REPORT_BOOK FOREIGN KEY(BOOK_REPORT_ID)
	REFERENCES TBL_BOOK_REPORT(ID) ON DELETE CASCADE
);

/*독후감 투표 테이블*/
CREATE TABLE TBL_VOTE(
	ID NUMBER CONSTRAINT PK_VOTE PRIMARY KEY,
	BOOK_REPORT_ID NUMBER NOT NULL,
	MEMBER_ID NUMBER NOT NULL,
	CREATED_DATE DATE DEFAULT SYSDATE,
	UPDATED_DATE DATE DEFAULT SYSDATE,
	CONSTRAINT FK_VOTE_BOOK_REPORT FOREIGN KEY(BOOK_REPORT_ID)
	REFERENCES TBL_BOOK_REPORT(ID) ON DELETE CASCADE,
	CONSTRAINT FK_VOTE_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID) ON DELETE CASCADE
);

/*공지사항 테이블*/
CREATE TABLE TBL_NOTICE(
	ID NUMBER CONSTRAINT PK_NOTICE PRIMARY KEY,
	NOTICE_TITLE VARCHAR2(1000) NOT NULL,
	NOTICE_DETAIL VARCHAR2(1000) NOT NULL,
	CREATED_DATE DATE DEFAULT SYSDATE,
	UPDATED_DATE DATE DEFAULT SYSDATE
);

/*(봉사단체가 등록하는)기부 프로그램 테이블*/
CREATE TABLE TBL_DONATION(
	ID NUMBER CONSTRAINT PK_DONATION PRIMARY KEY,
	DONATION_TITLE VARCHAR2(1000) NOT NULL,
	DONATION_DETAIL VARCHAR2(1000),
	VOLUNTEER_ID NUMBER NOT NULL,
	CREATED_DATE DATE DEFAULT SYSDATE,
	UPDATED_DATE DATE DEFAULT SYSDATE,
	CONSTRAINT FK_DONATION_VOLUNTEER FOREIGN KEY(VOLUNTEER_ID)
	REFERENCES TBL_VOLUNTEER(ID) ON DELETE CASCADE
);

/*파일 테이블(하위 테이블은 서브키로)*/
CREATE TABLE TBL_FILE(
	ID NUMBER CONSTRAINT PK_FILE PRIMARY KEY,
	FILE_NAME VARCHAR2(1000) NOT NULL,
	FILE_PATH VARCHAR2(1000) NOT NULL,
	CREATED_DATE DATE DEFAULT SYSDATE,
	UPDATED_DATE DATE DEFAULT SYSDATE
);

/*기부 프로그램 썸네일 파일*/
CREATE TABLE TBL_DONATION_FILE(
	ID NUMBER CONSTRAINT PK_DONATION_FILE PRIMARY KEY,
	DONATION_ID NUMBER NOT NULL,
	FILE_TYPE VARCHAR2(1000) DEFAULT 'IMAGE',
	CONSTRAINT FK_DONATION_FILE_FILE FOREIGN KEY(ID)
	REFERENCES TBL_FILE(ID) ON DELETE CASCADE,
	CONSTRAINT FK_DONATION_FILE_DONATION FOREIGN KEY(DONATION_ID)
	REFERENCES TBL_DONATION(ID) ON DELETE CASCADE
);

/*독서 토론 주제 테이블*/
CREATE TABLE TBL_DISCUSSION(
	ID NUMBER CONSTRAINT PK_DISCUSSION PRIMARY KEY,
	BOOK_ID NUMBER NOT NULL,
	DISCUSSION_TITLE VARCHAR2(1000) NOT NULL,
	DISCUSSION_DETAIL VARCHAR2(1000) NOT NULL,
	CREATED_DATE DATE DEFAULT SYSDATE,
	UPDATED_DATE DATE DEFAULT SYSDATE,
	CONSTRAINT FK_DISCUSSION_BOOK FOREIGN KEY(BOOK_ID)
	REFERENCES TBL_BOOK(ID) ON DELETE CASCADE
);

/*독서 토론 댓글 테이블*/
CREATE TABLE TBL_REPLY(
	ID NUMBER CONSTRAINT PK_REPLY PRIMARY KEY,
	DISCUSSION_ID NUMBER NOT NULL,
	MEMBER_ID NUMBER NOT NULL,
	REPLY_CONTENT VARCHAR2(1000) NOT NULL,
	CREATED_DATE DATE DEFAULT SYSDATE,
	UPDATED_DATE DATE DEFAULT SYSDATE,
	CONSTRAINT FK_REPLY_DISCUSSION FOREIGN KEY(DISCUSSION_ID)
	REFERENCES TBL_DISCUSSION(ID) ON DELETE CASCADE,
	CONSTRAINT FK_REPLY_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID) ON DELETE CASCADE
);

/*토론 대댓글 테이블*/
CREATE TABLE TBL_REPLY_REPLY(
	ID NUMBER CONSTRAINT PK_REPLY_REPLY PRIMARY KEY,
	REPLY_ID NUMBER NOT NULL,
	MEMBER_ID NUMBER NOT NULL,
	REPLY_REPLY_CONTENT VARCHAR2(1000) NOT NULL,
	CREATED_DATE DATE DEFAULT SYSDATE,
	UPDATED_DATE DATE DEFAULT SYSDATE,
	CONSTRAINT FK_REPLY_REPLY_REPLY FOREIGN KEY(REPLY_ID)
	REFERENCES TBL_REPLY(ID) ON DELETE CASCADE,
	CONSTRAINT FK_REPLY_REPLY_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID) ON DELETE CASCADE
);

/*토론 댓글, 대댓글 신고 테이블(서브키)*/ /*NOT NULL의 여부와 대댓글도 여기 넣어야하는지 고민중*/
CREATE TABLE TBL_REPLY_REPORT(
	ID NUMBER CONSTRAINT PK_REPLY_REPORT PRIMARY KEY,
	REPLY_ID NUMBER,
	REPLY_REPLY_ID NUMBER,
	CONSTRAINT FK_REPLY_REPORT_REPORT FOREIGN KEY(ID)
	REFERENCES TBL_REPORT(ID) ON DELETE CASCADE,
	CONSTRAINT FK_REPLY_REPORT_REPLY FOREIGN KEY(REPLY_ID)
	REFERENCES TBL_REPLY(ID) ON DELETE CASCADE,
	CONSTRAINT FK_REPLY_REPORT_REPLY_REPLY FOREIGN KEY(REPLY_REPLY_ID)
	REFERENCES TBL_REPLY_REPLY(ID) ON DELETE CASCADE
);

/*개인 문의 테이블*/
CREATE TABLE TBL_MEMBER_INQUIRY(
	ID NUMBER CONSTRAINT PK_MEMBER_INQUIRY PRIMARY KEY,
	MEMBER_ID NUMBER NOT NULL,
	MEMBER_INQUIRY_TYPE VARCHAR2(1000) NOT NULL,
	MEMBER_INQUIRY_TITLE VARCHAR2(1000) NOT NULL,
	MEMBER_INQUIRY_DETAIL VARCHAR2(1000) NOT NULL,
	MEMBER_INQUIRY_STATUS VARCHAR2(1000) DEFAULT '처리중',
	CREATED_DATE DATE DEFAULT SYSDATE,
	UPDATED_DATE DATE DEFAULT SYSDATE,
	CONSTRAINT FK_MEMBER_INQUIRY_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID) ON DELETE CASCADE
);

/*단체 문의 테이블*/
CREATE TABLE TBL_VOLUNTEER_INQUIRY(
	ID NUMBER CONSTRAINT PK_VOLUNTEER_INQUIRY PRIMARY KEY,
	VOLUNTEER_ID NUMBER NOT NULL,
	VOLUNTEER_INQUIRY_TYPE VARCHAR2(1000) NOT NULL,
	VOLUNTEER_INQUIRY_TITLE VARCHAR2(1000) NOT NULL,
	VOLUNTEER_INQUIRY_DETAIL VARCHAR2(1000) NOT NULL,
	VOLUNTEER_INQUIRY_STATUS VARCHAR2(1000) DEFAULT '처리중',
	CREATED_DATE DATE DEFAULT SYSDATE,
	UPDATED_DATE DATE DEFAULT SYSDATE,
	CONSTRAINT FK_VOLUNTEER_INQUIRY_VOLUNTEER FOREIGN KEY(VOLUNTEER_ID)
	REFERENCES TBL_VOLUNTEER(ID) ON DELETE CASCADE
);

/*개인문의 답변 테이블*/
CREATE TABLE TBL_MEMBER_INQUIRY_ANSWER(
	ID NUMBER CONSTRAINT PK_MEMBER_INQUIRY_ANSWER PRIMARY KEY,
	MEMBER_INQUIRY_ID NUMBER,
	CREATED_DATE DATE DEFAULT SYSDATE,
	UPDATED_DATE DATE DEFAULT SYSDATE,
	CONSTRAINT FK_MEMBER_INQUIRY_ANSWER FOREIGN KEY(MEMBER_INQUIRY_ID)
	REFERENCES TBL_MEMBER_INQUIRY(ID) ON DELETE CASCADE
);

/*단체문의 답변 테이블*/
CREATE TABLE TBL_VOLUNTEER_INQUIRY_ANSWER(
	ID NUMBER CONSTRAINT PK_VOLUNTEER_INQUIRY_ANSWER PRIMARY KEY,
	VOLUNTEER_INQUIRY_ID NUMBER,
	CREATED_DATE DATE DEFAULT SYSDATE,
	UPDATED_DATE DATE DEFAULT SYSDATE,
	CONSTRAINT FK_VOLUNTEER_INQUIRY_ANSWER FOREIGN KEY(VOLUNTEER_INQUIRY_ID)
	REFERENCES TBL_VOLUNTEER_INQUIRY(ID) ON DELETE CASCADE
);


